### PR TITLE
add Ikea manufacturer and firmware

### PR DESCRIPTION
**Pull request by glueckself**
Source: http://fw.ota.homesmart.ikea.net/feed/version_info.json

### CODE REVIEW

**Comment by glueckself** [comment]
There is an issue with the file version. For example with `http://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.046/bin/10076692-zingo_lds_bulb_hwpwmcs_ws-1.0.012.ota.ota.signed`, the `version_info.json` reports `fw_file_version_LSB | 18` `fw_file_version_MSB | 1`, however in the index.json its reported as `65554`, which is not detected as a valid update.

Please let me know how to proceed. Thanks!

**Comment by Koenkk** [comment]
Ikea already has it's own update site, why add it here?

**Comment by glueckself** [comment]
To be honest, I haven't looked deep into the code, sorry for that.

I'm using the IKEA LED2005R5 with the last version 1.0.012 from 20201111. The versions in the url `http://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.046/bin/10035534-2.1-TRADFRI-bulb-ws-gu10-2.3.087.ota.ota.signed` made me think that there should be an update (however, I'm not 100% sure that this is the right firmware link for my bulbs) but zigbee2mqtt said that there was no update. So I found the index file and saw that Ikea was missing and added it. After creating the pull request, I tried to test with the branch on my repo, but that didn't work.

I'll look into z2m, thanks for the hint! I guess we can close this pull request?

**Comment by Koenkk** [comment]
yes this can be closed.

**Pull request closed without merging**
