### PR TITLE
Bosch BTH-RA (Radiator thermostat II): Add firmware 3.05.09 from 11th of december 2023

### PR DESCRIPTION
**Pull request by DerDreschner**
This week, bosch released a new firmware for their radiator thermostat II. It has the version number 3.05.09 and reduces the probability of occurrence of error "E04" [according to their changelog](https://www.bosch-smarthome.com/uk/en/release-notes/bosch-smart-home-system/2023-12-11.html). As far as I understood the user posts in their community, this error indicates a broken motor. So, quite an important update.

As they don't release an official download, I had to sniff the firmware once again. To test the package, I updated another thermostat afterwards over Z2M successfully.

Enjoy and happy Christmas everyone!

### CODE REVIEW

**Comment by mmattel** [comment]
@DerDreschner many thanks for your warm Christmas wishes and the nice gift provided 😃
Merry Christmas too 👋

**Comment by Koenkk** [comment]
Merry Christmas! 🌲

**Comment by mmattel** [comment]
@Koenkk @DerDreschner info: the new firmware version appears as `3.05.05` (same as the former one) and not as `3.05.09`...

**Comment by DerDreschner** [comment]
@mmattel : Sounds like the version string wasn't updated inside Z2M during the firmware update. The firmware reports correctly on my end:
image
Try to retrieve the following settings: https://github.com/Koenkk/zigbee2mqtt/issues/17740#issuecomment-1556146513

**Comment by mmattel** [comment]
Upgrade success from my side, but:
image
I needed about 3 attempts to succeed and it shows that the issue I created and you referenced is still valid... 😢

**Comment by MMeinhardt1** [comment]
Many thanks for your tireless work

**Pull request merged**
