### PR TITLE
add snzb-06p_1.0.5.ota

### PR DESCRIPTION
**Pull request by North-Sea-ice-free**
Added OTA files for SONOFF device SNZB-06P

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by TZodiacK** [comment]
Hello!
I see that this has been merged 2 weeks ago, but my Z2M has a SNZB-06P with old firmware and it does not appear the OTA update, it does not even show the device as updatable. Am I doing something wrong or missing a step?

My Z2M is updated to latest version.

**Comment by liangjia2019** [comment]
> Hello! I see that this has been merged 2 weeks ago, but my Z2M has a SNZB-06P with old firmware and it does not appear the OTA update, it does not even show the device as updatable. Am I doing something wrong or missing a step?
> 
> My Z2M is updated to latest version.

Hi TZodiacK:
I think if you want to receive an update prompt for SNZB-06P, you first need to update your zigbee-herdsman-converters separately. I have given them OTA capability.
you first need to update your zigbee-herdsman-converters 15.122.0 
https://github.com/Koenkk/zigbee-herdsman-converters/pull/6512

**Comment by TZodiacK** [comment]
Thank you for the reply, is there a guide of how to update the zigbee-herdsman-converters on homeassistant besides using the dev branch of Z2M?

**Pull request merged**
