### PR TITLE
Added OTA for Develco SMSZB-120, fw 4.02

### PR DESCRIPTION
**Pull request by TheStigh**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, note for in order for this to work with z2m, `ota: ota.zigbeeOTA` has to be added to https://github.com/Koenkk/zigbee-herdsman-converters/blob/a062b38b18b665c935c13208b926208203dbdb3d/devices/develco.js#L141

**Comment by TheStigh** [comment]
> 
> 
> Thanks, note for in order for this to work with z2m, `ota: ota.zigbeeOTA` has to be added to https://github.com/Koenkk/zigbee-herdsman-converters/blob/a062b38b18b665c935c13208b926208203dbdb3d/devices/develco.js#L141

Already in dev (PR will be made after testing), waited for your acceptance of the PR to do the test :)

**Comment by TheStigh** [comment]
@Koenkk  Got this error when trying to update:

`Zigbee2MQTT:error 28-06-2021 17:51:44: Update of '0x0015bc0031005323' failed (Image is truncated: not long enough to contain a valid tag)`

Any idea ?

**Comment by Koenkk** [comment]
@TheStigh looks like the file is not a valid zigbee OTA file. This validation is done here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/beb1324cba9a7db7eeca53fc4d44de2aeec723d4/lib/ota/common.js#L103

**Comment by TheStigh** [comment]
> 
> 
> @TheStigh looks like the file is not a valid zigbee OTA file. This validation is done here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/beb1324cba9a7db7eeca53fc4d44de2aeec723d4/lib/ota/common.js#L103 OR the validation code is bugged, try removing this line: https://github.com/Koenkk/zigbee-herdsman-converters/blob/beb1324cba9a7db7eeca53fc4d44de2aeec723d4/lib/ota/common.js#L129

A 'dumb' question, but how do I remove this frm z-h-c when running the add-on Edge on my dev?
I can do a bash into the container, but from there...?

**Comment by Koenkk** [comment]
> But after restart of Z2M, the line is back ?...

You should not restart z2m via HA, instead exit the container and do: `docker restart CONTAINER_ID`

**Comment by TheStigh** [comment]
> 
> 
> > But after restart of Z2M, the line is back ?...
> 
> You should not restart z2m via HA, instead exit the container and do: `docker restart CONTAINER_ID`

Update started, let's see how it goes.... I'll update here as soon as it are either finished/failed.

**Comment by TheStigh** [comment]
@Koenkk 

So update went fine, just took almost 4 hrs :) Should I make a PR to remove the L129, or do you want to have it a look at it or what? I have 3 more devices where i can test the upgrade if you want to look at the code ...

**Comment by Koenkk** [comment]
@pedrolamas do you understand why verification fails for the OTA file in this pr?

**Comment by TheStigh** [comment]
@Koenkk FYI, same issue for this [IKEA bulb](https://www.zigbee2mqtt.io/devices/LED1732G11.html#ikea-led1732g11)

**Comment by Koenkk** [comment]
@TheStigh probably due to https://www.zigbee2mqtt.io/information/ota_updates.html#using-the-ikea-tradfri-test-server

**Comment by TheStigh** [comment]
@Koenkk  What should I do? Tomorrow I'm off, so it is either today or for next release to do the updated SMSZB-120 converter supporting OTA + minor adjustments... If I make the PR, we must do something with the `common.js` ... The PR are ready to go...

**Comment by pedrolamas** [comment]
> @pedrolamas do you understand why verification fails for the OTA file in this pr?

I will try to check the file later today, I'm not on my computer right now... I do have to admit, I'm surprised the update worked when the file failed validation!

**Comment by TheStigh** [comment]
> 
> 
> @TheStigh probably due to https://www.zigbee2mqtt.io/information/ota_updates.html#using-the-ikea-tradfri-test-server

Added the advanced but still get same error as the SMSZB-120:
`Zigbee2MQTT:error 29-06-2021 19:53:12: Update of 'Utelys Hoveddør' failed (Image is truncated: not long enough to contain a valid tag)`

IKEA are on my production machine, SMSZB are on my dev machine.

**Comment by pedrolamas** [comment]
I've tested the firmware file and I know why it failed validation!

The like below was identified as being an EBL block as it starts with 0x0, but obviously it is now (the whole block is 0x0)

image

I can also see that no blocks on this OTA file do not match EBL or GBL, so they are something else...

We need to improve the type detection to avoid these issues, either by just checking that the whole thing is not null or that the block has a minimum length. I will try both options and see which one works better, if anyone has a better idea please do share!

**Comment by pedrolamas** [comment]
Found a better solution for these cases, as we can check for 0xe350 at position 6, so will now add this to EBL identification!

**Comment by pedrolamas** [comment]
@TheStigh The latest z2m release should have the original problem now fixed, have you been able to confirm?

**Comment by TheStigh** [comment]
> 
> 
> @TheStigh The latest z2m release should have the original problem now fixed, have you been able to confirm?

@pedrolamas 

I can confirm it works in Dev, but somehow the latest updated device didn't manage to get into the July-release. So I cannot test in release unfortunately.

**Pull request merged**
