### PR TITLE
TS0601_thermostat firmware v1.1.7

### PR DESCRIPTION
**Pull request by artem-sedykh**
[Smart Life app](https://play.google.com/store/apps/details?id=com.tuya.smartlife&hl=ru&gl=US) response:  
```json
{
  "result": [
    {
      "devType": 0,
      "typeDesc": "Модуль ZigBee",
      "type": 3,
      "firmwareDeployTime": 1615986875,
      "version": "1.1.7",
      "url": "https://images.tuyaeu.com/smart/firmware/upgrade/202103/1615190575-si32_zg_uart_connect_sleep_ZS5_ty_OTA_1.1.7.bin",
      "timeout": 60,
      "currentVersion": "1.1.5",
      "upgradingDesc": "Please keep the power of the device connected during the upgrade process, please be patient.",
      "upgradeStatus": 1,
      "controlType": 1,
      "fileSize": "234174",
      "upgradeType": 0,
      "lastUpgradeTime": 0,
      "md5": "626634acc0edc3173c7b1770f7a94e75",
      "desc": "Firmware upgrade"
    },
    {
      "devType": 0,
      "typeDesc": "Модуль микроконтроллера",
      "type": 9,
      "timeout": 60,
      "currentVersion": "2.0.0",
      "upgradeStatus": 0,
      "controlType": 1,
      "lastUpgradeTime": 0
    }
  ],
  "t": 1620821837774,
  "success": true,
  "status": "ok"
}
```

### CODE REVIEW

**Comment by artem-sedykh** [comment]
[Smart Life app](https://play.google.com/store/apps/details?id=com.tuya.smartlife&hl=ru&gl=US) response:  
```json
{
  "result": [
    {
      "devType": 0,
      "typeDesc": "Модуль ZigBee",
      "type": 3,
      "firmwareDeployTime": 1615986875,
      "version": "1.1.7",
      "url": "https://images.tuyaeu.com/smart/firmware/upgrade/202103/1615190575-si32_zg_uart_connect_sleep_ZS5_ty_OTA_1.1.7.bin",
      "timeout": 60,
      "currentVersion": "1.1.5",
      "upgradingDesc": "Please keep the power of the device connected during the upgrade process, please be patient.",
      "upgradeStatus": 1,
      "controlType": 1,
      "fileSize": "234174",
      "upgradeType": 0,
      "lastUpgradeTime": 0,
      "md5": "626634acc0edc3173c7b1770f7a94e75",
      "desc": "Firmware upgrade"
    },
    {
      "devType": 0,
      "typeDesc": "Модуль микроконтроллера",
      "type": 9,
      "timeout": 60,
      "currentVersion": "2.0.0",
      "upgradeStatus": 0,
      "controlType": 1,
      "lastUpgradeTime": 0
    }
  ],
  "t": 1620821837774,
  "success": true,
  "status": "ok"
}
```

**Comment by Koenkk** [comment]
Thanks!

**Comment by brokenmass** [comment]
@Koenkk / @artem-sedykh  : do you have the changelog for this firmware ?

**Comment by artem-sedykh** [comment]
@brokenmass  Hey! the manufacturer did not provide a changelog

**Comment by vladi1234** [comment]
Hello, I would like to know which thermostats are these files for?

```
modelID:?
manufacturerName:?
model:?
vendor:?
```

**Pull request merged**
