### PR TITLE
Updated Hue images

### PR DESCRIPTION
**Pull request by TheJulianJES**
This PR updates images for Silicon Labs based Hue lights.
Release notes:
- https://www.philips-hue.com/en-us/support/release-notes/lamps

The version adds some new effects.
The friendly Hue version of these images are 1.122.2 and 1.122.3.

### CODE REVIEW

**Comment by mundschenk-at** [comment]
I updated one of my Hue Twilights to `1.22.2?` via BT a few days ago, so it's probably `1.22.2`. According to https://hueblog.com/2024/10/09/firmware-update-to-version-1-122-2-for-almost-all-hue-lamps/ it should include four new effects:
* Cosmos
* Enchant
* Sunbeam
* Underwater

**Comment by DerDreschner** [comment]
I've updated 8 hue light bulbs using the change from this PR (all using file version `16786690`).

As far as I'm concerned, I see no reason not to merge it.

**Review by DerDreschner — APPROVED** [review]

**Comment by TheJulianJES** [comment]
Thanks for the info! I also did a test on some Hue lights now and everything seems to work as expected.

**Comment by Koenkk** [comment]
Thanks @TheJulianJES !

**Pull request merged**
