### PR TITLE
TV02-Zigbee OTA-update version 2.0.4

### PR DESCRIPTION
**Pull request by vladi1234**
https://github.com/Koenkk/zigbee-OTA/issues/104#issue-1190993754

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by vladi1234** [comment]
Hallo @Koenkk, 
something went wrong. I get error log.

Error Failed to check if update available for 'Термостат в Гостиной' (images.find is not a function)

**Comment by davidjb** [comment]
@vladi1234 The reason is that the JSON from your PR was invalid; see https://github.com/Koenkk/zigbee-OTA/pull/107.

**Comment by vladi1234** [comment]
Thank @davidjb,
I didn't do my JSON with add.js so I missed ",".

**Comment by vladi1234** [comment]
Hello @Koenkk, 
when I update I get a buffer error.


node scripts/updateall.js
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:371:5)
    at boundsError (node:internal/buffer:84:11)
    at Buffer.readUInt16LE (node:internal/buffer:243:5)
    at Object.parseImage (/home/pi/zigbee-OTA-master/lib/ota.js:17:34)
    at main (/home/pi/zigbee-OTA-master/scripts/add.js:65:24)
    at Object.<anonymous> (/home/pi/zigbee-OTA-master/scripts/add.js:136:8)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
node:child_process:828
    err = new Error(msg);
          ^

Error: Command failed: node ./scripts/add.js "images/Tuya/TV02-Zigbee_MCU_Module_2.0.4_164155152229641863dfc.bin" ""
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:371:5)
    at boundsError (node:internal/buffer:84:11)
    at Buffer.readUInt16LE (node:internal/buffer:243:5)
    at Object.parseImage (/home/pi/zigbee-OTA-master/lib/ota.js:17:34)
    at main (/home/pi/zigbee-OTA-master/scripts/add.js:65:24)
    at Object.<anonymous> (/home/pi/zigbee-OTA-master/scripts/add.js:136:8)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at /home/pi/zigbee-OTA-master/scripts/updateall.js:8:38
    at Array.forEach (<anonymous>)
    at main (/home/pi/zigbee-OTA-master/scripts/updateall.js:7:15)
    at Object.<anonymous> (/home/pi/zigbee-OTA-master/scripts/updateall.js:15:8)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(831) [Uint8Array] [
      110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
      108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  54,  52,
       10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
      112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
       97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
       32,  32,  94,  10,  10,  82,  97, 110, 103, 101,  69, 114,
      114, 111, 114,  32,  91,  69,  82,  82,  95,  66,  85,  70,
       70,  69,  82,  95,  79,  85,  84,  95,  79,  70,  95,  66,
       79,  85,  78,  68,
      ... 731 more items
    ]
  ],
  pid: 4060968,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(831) [Uint8Array] [
    110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
    108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  54,  52,
     10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
    112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
     97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
     32,  32,  94,  10,  10,  82,  97, 110, 103, 101,  69, 114,
    114, 111, 114,  32,  91,  69,  82,  82,  95,  66,  85,  70,
     70,  69,  82,  95,  79,  85,  84,  95,  79,  70,  95,  66,
     79,  85,  78,  68,
    ... 731 more items
  ]
}
```

I hope you can help me.

**Pull request merged**
