### PR TITLE
Add OTA files for Perenio `PEHPL01`, `PECMS01` and `PECLS01`

### PR DESCRIPTION
**Pull request by Otnow**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by VOVAiS** [comment]
Hay @Otnow 
and there is an opportunity to roll back PEHPL0X to firmware 1.3.11.
firmware 1.3.43 is buggy

**Comment by Otnow** [comment]
> Hay @Otnow
> There is an opportunity to roll back PEHPL0X to firmware 1.3.11.
> firmware 1.3.43 is buggy

It's a pity that firmware _1.3.43_ causes problems (what exactly is wrong?).

Unfortunately, firmware _1.3.11_ could not be found, but there are 2 others (_do not forget to extract the firmware file from the archive_):

- _1.3.33_: [007B-0141-0000285D-good_image.zip](https://github.com/Koenkk/zigbee-OTA/files/10387000/007B-0141-0000285D-good_image.zip)

- _1.3.41_: [007B-0141-00002865-good_image_PL_1_3_41.zip](https://github.com/Koenkk/zigbee-OTA/files/10387009/007B-0141-00002865-good_image_PL_1_3_41.zip)

**Comment by VOVAiS** [comment]
If the power goes out of the socket, it may not return to the network. Low iq. Constantly falling off

**Comment by VOVAiS** [comment]
downgrading the firmware does not work
my file

> [
    {
         "fileVersion":10333,
         "fileSize":408926,
         "manufacturerCode":123,
         "imageType":321,
         "sha512":"c3e0911758f7e840f1f183cd427444bd7daebe8905754cc3d81ee3007f88b75e15cf1b39f7156407ea3459eb36d9f2dc10e280c2fce81953e8cb50b7752b9aab",
         "url": "007B-0141-0000285D-good_image.zigbee",
         "modelId": "PEHPL0X",
         "path": "007B-0141-0000285D-good_image.zigbee",
         "force": true
     }
]

I click update and the update does not start

**Comment by Otnow** [comment]
> downgrading the firmware does not work

Are you trying this guide?: https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#local-ota-index-and-firmware-files

If yes, then after changing the settings, you need to restart _z2m_.

**Comment by VOVAiS** [comment]
Go telegram?

**Pull request merged**
