### PR TITLE
Added new OTA for lumi.relay.c2acn01

### PR DESCRIPTION
**Pull request by zvldz**

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by McGiverGim** [comment]
I suppose this will need to uncomment this too in the devices?

https://github.com/Koenkk/zigbee-herdsman-converters/blob/5744a895a8bbb951a5524d4ba5fd4c06d309dbee/devices/xiaomi.js#L1302

**Comment by Koenkk** [comment]
@zvldz can you confirm https://github.com/Koenkk/zigbee2mqtt/issues/7112 does not occur with this fw?

**Comment by zvldz** [comment]
Do you mean current, voltage and energy values?

**Comment by zvldz** [comment]
I have all the values.
But I am not using this relay with zigbee2mqtt right now.
I use this integration https://github.com/AlexxIT/XiaomiGateway3/ for the relay.
But if you want the logs, I can do it.

**Pull request merged**
