### PR TITLE
added ota files for microdim 07 dimmer/switch

### PR DESCRIPTION
**Pull request by Kilill**
ota files from ecodim.nl for "Eco-Dim.07/Eco-Dim.10" uploaded after permission from Gabbe van der Zwan

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by erlendk** [comment]
Hi, tried to update my Eco-Dim.07 Zigbee Pro today. Got a similar message to the one posted here: https://github.com/Koenkk/zigbee2mqtt/issues/15279#issuecomment-1340717856

When requesting a check for new updates on this device, the Z2M log reads: 

> Got OTA request '{"fieldControl":0,"manufacturerCode":4714,"imageType":44,"fileVersion":50947376}'

This indicates that the manufacturer code 4098 (Tuya) used for the OTA-file added in this commit should not be found by this update request. The file version is also way off (10) from mine (50947376). BTW: Z2M reports my FW-version to be 3.09 with build date 20210228.

The first thing that strikes me is that the manufacturer code of this update says that it is for a Tuya device. This could of course be due to some white-label product strategy, but my device reports a different code (not found in https://github.com/Koenkk/zigbee-OTA/blob/master/scripts/add.js). What manufacturer code does your device report @Kilill? And how did you obtain the OTA-file (ZB21S3_HZC_Dimmer1_ECO_1.01_20221021.ota)? I cannot find any firmware readily available from https://www.ecodim.nl.

**Comment by Kilill** [comment]
Same as you, 
see: [zigbee2mqtt: issue 15473](https://github.com/Koenkk/zigbee2mqtt/issues/15473)
I have notified Microdim about it. But it was just before the hole Christmas/New Year debacle, so haven't heard anything back yet, i'l poke them in the coming week,  i'l upload the file as soon as I get it.

**Comment by erlendk** [comment]
Ah, sorry. Poor investigation from my side.

**Pull request merged**
