### PR TITLE
Re-add `QBCZ14LM, QBCZ15LM` OTA updates

### PR DESCRIPTION
**Pull request by z-x-f**
UpdateLog:  Fix known issues.
```json
[
    {
        "fileName": "20240722115926_OTA_lumi.plug.sacn02_0.0.0_0052_20240719_986BEB.ota",
        "modelId": "lumi.plug.sacn02"
    },
    {
        "fileName": "20240722115628_OTA_lumi.plug.sacn03_0.0.0_0038_20240719_39CCF1.ota",
        "modelId": "lumi.plug.sacn03"
    }
]
```

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by z-x-f** [comment]
@Koenkk Uh, re-adding it like this doesn't seem to have any effect...

**Comment by TheJulianJES** [comment]
The images and changes were already in the repo, so there is no diff between this PR (or the squashed commit: https://github.com/Koenkk/zigbee-OTA/commit/ef5be408cf98af70bdb337f03f0296ecce75d1c4) and upstream `master` branch.
What was the reason for this PR when they were already merged in https://github.com/Koenkk/zigbee-OTA/pull/610?

**Comment by Koenkk** [comment]
It was already indeed

**Comment by z-x-f** [comment]
I didn't include the `modelId` when I first submitted it, so the script didn't move the old ota file to `images1` as expected. I also found that re-add the ota file didn't help because it had already been submitted.

**Comment by Koenkk** [comment]
I reverted all your changes, please make a new PR

**Pull request merged**
