### PR TITLE
Update SIN-4-1-20

### PR DESCRIPTION
**Pull request by AlexisPolegato**
Update SIN-4-1-20 FW 1 to V2.31.0
Add SIN-4-1-20 FW 2 V1.1.1

### CODE REVIEW

**Comment by Koenkk** [comment]
Please use the [add](https://github.com/Koenkk/zigbee-OTA#adding-new-and-updating-existing-ota-files) script when adding OTA files, this makes sure they get added to the `index.json`.

**Comment by Koenkk** [comment]
I see the firmwares are for the same device, why did you upload both firmwares? (only 1 of them will be used)

**Comment by AlexisPolegato** [comment]
The device has 2 different firmwares ; both can be updated.

**Comment by Koenkk** [comment]
I see, just noticed that the `imageType` is different, thanks!

**Pull request merged**
