### PR TITLE
DIY lywsd03mmc OTA with changed manufacturer code

### PR DESCRIPTION
**Pull request by devbis**
During the last OTA I changed manufacturer code to custom to avoid struggling for image type numbers for updates. 
My suggestion is to put multiple DIY manufacturers to the same folder, I doubt there will be many of them. 
I also considered using `DIY_devbis` as a folder, but decided that it is redundant here.

Firmware here is the same as in Telink folder with a correct manufacturer type in header to mute errors about missing OTA in the repo.

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by mrmaximas** [comment]
@devbis hi! it is possible to flash LYWSD03MMC with pvvx fw to yours? how to do it right? I've tried several ota_index options, but couldn't change the firmware to yours. Thanks!

**Comment by mrmaximas** [comment]
@devbis hi! it is possible to flash LYWSD03MMC with pvvx fw to yours? how to do it right? I've tried several ota_index options, but couldn't change the firmware to yours. Thanks!
Screenshot 2024-11-12 at 20 54 42

**Comment by devbis** [comment]
@mrmaximas You can use a file from this comment https://github.com/devbis/z03mmc/issues/118#issuecomment-1942371299 and use local OTA json file

**Comment by mrmaximas** [comment]
@devbis thanks! it's works! are you planning to implement the measurement interval setting like pvvx?

**Comment by devbis** [comment]
> are you planning to implement the measurement interval setting like pvvx?

I don't have such plans, it is incompatible with zigbee reporting configuration in general

**Pull request merged**
