### PR TITLE
Add _TZE200_cpmgn2cf TRV to OTA

### PR DESCRIPTION
**Pull request by consi**
TRV _TZE200_cpmgn2cf works fine with firmware `images/Tuya/1615190575-si32_zg_uart_connect_sleep_ZS5_ty_OTA_1.1.7.bin` so it can be added

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by newlund** [comment]
Just updated zigbee2mqtt and now I see this OTA update available for my Tuya T0601 _TZE200_cpmgn2cf.
Really safe to update? :)

**Comment by newlund** [comment]
> @newlund have you eventually updated? I just received the OTA alert today... lol

Yes, I did eventually update my thermostats after months of hesitation :)
They seem to work fine after the update.

**Comment by auanasgheps** [comment]
Thanks for the feedback, I'll go ahead!

**Pull request merged**
