### PR TITLE
Add Neo NAS-WR01B(TS011F_plug) OTA file

### PR DESCRIPTION
**Pull request by zvldz**

### CODE REVIEW

**Comment by Koenkk** [comment]
- Does this firmware work on all manufacturer names of the TS011F plugs?
- Does this firmware influence the reporting capability, it is known that newer firmwares do not support this anymore and rely on polling instead.

Note to self; after this merge https://github.com/Koenkk/zigbee-herdsman-converters/pull/3848

**Comment by zvldz** [comment]
works on TS011F_plug_3 after updating it becomes TS011F_plug_1

**Comment by Koenkk** [comment]
It doesn't seem to work for all, my TS011F_plug_3 requests a different image type:

Screenshot 2022-02-10 at 19 39 27

DB entry:

```
{"id":2,"type":"Router","ieeeAddr":"0xb4e3f9fffe20709c","nwkAddr":20416,"manufId":4098,"manufName":"_TZ3000_cphmq0q7","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65534":0,"modelId":"TS011F","manufacturerName":"_TZ3000_cphmq0q7","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1}},"seMetering":{"attributes":{"divisor":100,"multiplier":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1121114317},"lastSeen":1644518318464,"defaultSendRequestWhen":"immediate"}
```

**Comment by zvldz** [comment]
mitm proxy (charles proxy) and android emulator (genymotion with arm translation) and tuya application version 3.12.6
I can explain in more detail if you need.

**Comment by Koenkk** [comment]
It would be great if you could write a short tutorial on this, could you make a PR for the docs? (https://github.com/Koenkk/zigbee2mqtt.io/tree/master/docs/how_tos) Then also others can benefit from this.

**Comment by zvldz** [comment]
Okay, I'll try to put everything from the beginning and write a little tutorial.  I hope it doesn't stop working.

**Comment by zvldz** [comment]
But it is sure will not be a very detailed manual. Where each step will be written with screenshots.

**Comment by Koenkk** [comment]
No problem, if the basic instructions are there I can extend.

**Comment by Koenkk** [comment]
@zvldz thanks, I've adapted the guide to also work on non Linux system (used Mac in my case) and to use free software which does not require registration. Could you review this? https://github.com/Koenkk/zigbee2mqtt.io/pull/1243

**Pull request merged**
