### PR TITLE
Update firmware for Bosch ``BTH-RA`` to january 2023 release

### PR DESCRIPTION
**Pull request by DerDreschner**
Thanks to the great [@ZigbeeOta](https://github.com/compujuckel/ZigbeeOtaExtractor) from @compujuckel, I was able to sniff and extract the latest firmware update for the Bosch BTH-RA (also known as Smart Thermostat 2).

Release Notes (or whatever Bosch calls like that): https://www.bosch-smarthome.com/de/de/service/aktuelle-meldungen/release-infos/system-solutions/2023-01-30.html

### CODE REVIEW

**Comment by compujuckel** [comment]
Glad to see that someone successfully used the extractor :)

Is the title of this issue correct? You updated the OTA file of BTH-RA, but your title says BSP-FZ2
Just want to make sure we aren't mixing up files here

**Comment by DerDreschner** [comment]
> Is the title of this issue correct? You updated the OTA file of BTH-RA, but your title says BSP-FZ2 Just want to make sure we aren't mixing up files here
Ha, good catch! I tried to get the update for the BSP-FZ2 as well. That's why I mixed it up a little bit. But the file is for the BTH-RA. :dancing_men:

**Comment by TheJulianJES** [comment]
Unrelated to the PR, but there's another OTA extractor here: https://github.com/zigpy/zigpy-cli/pull/29 (install code can be provided too).

**Comment by Koenkk** [comment]
Cool, thanks!

**Comment by mldytech** [comment]
Thanks for providing the update, unluckily I got the following error on all trv's after upgrading:

`Zigbee2MQTT:error 2023-03-12 12:10:16: Failed to configure 'bosch-thermo-2', attempt 1 (Error: Bind 0x18fc26000009739b/1 hvacThermostat from '0x00124b002a1b0045/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7))`

I already tried repairing, re-configuring and re-powering the device. Do you guys have any idea? If it fits better, I also can create an according issue.

**Comment by mmattel** [comment]
Interresting, I just upgraded both of my thermostats.
The first one upgraded flawless.
For the second one I needed to power off/on the thermostat via battery removal and then I had to restart the container running  zigbbee2mqtt. Finally it worked and command changing settigs were able to be set, both via HomeAssistant and zigbee2mqtt.
I strongly believe that the issue is thermostat related and is (hopefully) fixed with the new firmware.

**Comment by mldytech** [comment]
I managed to fix it, had to stop the container, hard reset (remove battery) the device and start the container again. After that the correct version was displayed. Nevertheless, one device seemed to not update correctly, had to upgrade the firmware again. I initially started all OTA's for my TRVs simultaneously, maybe that was a mistake.

**Comment by DerDreschner** [comment]
@mmattel and @mldytech : I guess that's expected behavior. I had to remove the batteries on my first thermostat to get a responding device, too. Although I updated it through the Bosch Smart Home App. The app itself states that it is normal to have a non-responding thermostat for up to 2 hours after the update. In case someone needs to change settings earlier or nothing happens after that time, it also recommends to push the button on the thermostat or remove the batteries. My second thermostat updated flawlessly over Zigbee2MQTT.

So, sorry for the inconvenience! But I'm glad that it worked after a restart. :smiley:

**Comment by mmattel** [comment]
I would like to take the chance to say thanks for providing the OTA, really appreciated !

**Comment by MMeinhardt1** [comment]
Is it possible to update the thermostat outside from the Bosch app and outside from zigbee2mqtt? I use the iobroker zigbee adapter. 

Many thanks

**Comment by docgalaxyblock** [comment]
*Note for other users that were linked here:* There is a [newer firmware PR #306](#306)

**Pull request merged**
