### PR TITLE
Add NodOn manufacturer and OTA File

### PR DESCRIPTION
**Pull request by AlexisPolegato**
Add NodOn manufacturer and NodOn SIN-4-RS-20 V2.26 OTA File

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by Wireheadbe** [comment]
Awesome! Great to see NodOn here! :)

**Comment by Wireheadbe** [comment]
Altough I do get an error when updating:
```
Info 2023-06-23 18:52:46MQTT publish: topic 'zigbee2mqtt/LenaRolluik', payload '{"device":{"applicationVersion":43,"dateCode":"2020","friendlyName":"LenaRolluik","hardwareVersion":50,"ieeeAddr":"0x9035eafffea4c9ac","manufacturerID":4747,"manufacturerName":"NodOn","model":"SIN-4-RS-20","networkAddress":46457,"powerSource":"Mains (single phase)","stackVersion":103,"type":"Router","zclVersion":3},"last_seen":"2023-06-23T16:52:50.958Z","linkquality":98,"position":100,"state":"OPEN","tilt":100,"update":{"installed_version":523,"latest_version":538,"state":"available"},"update_available":true}'
Info 2023-06-23 18:52:46MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'LenaRolluik' failed (No image available for imageType '265')","meta":{"device":"LenaRolluik","status":"update_failed"},"type":"ota_update"}'
Info 2023-06-23 18:52:46MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"LenaRolluik"},"error":"Update of 'LenaRolluik' failed (No image available for imageType '265')","status":"error","transaction":"st0dw-1"}'
Error 2023-06-23 18:52:46Update of 'LenaRolluik' failed (No image available for imageType '265')
```

"No image available for imageType '265'" - on latest -dev :)

**Comment by aurel32** [comment]
I just upgraded to zigbee2mqtt 1.32.0 as I was eager to test this feature. Unfortunately I have the exact same issue about `imageType '265'`. I tried on 3 different modules, currently running firmware 521 for two of them and 523 for another one.

**Pull request merged**
