### PR TITLE
update

### PR DESCRIPTION
**Pull request by weihuan1111**
Change-Id: Ia9b68eda7c054b5c0f1feeadf0a0e1e1b47da3c2

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by digiblur** [comment]
@weihuan1111 this link is 403'ing so the OTA update fails

**Comment by Koenkk** [comment]
The old url also doesn't work anymore (access denied)

**Comment by digiblur** [comment]
> The old url also doesn't work anymore (access denied)

I could see this happening more.  Not a bad idea to require in the future that firmware be uploaded/linked to this github repo?

**Comment by Koenkk** [comment]
@digiblur yes, definitely!

**Comment by digiblur** [comment]
fix - https://github.com/Koenkk/zigbee-OTA/pull/298

**Pull request merged**
