### PR TITLE
Add custom firmware from pvvx for Xiaomi LYWSD03MMC

### PR DESCRIPTION
**Pull request by kwiateusz**
Resository the file came from: https://github.com/pvvx/ZigbeeTLc

### CODE REVIEW

**Comment by Koenkk** [comment]
@devbis @krzysztof-kwitt asking because of https://github.com/Koenkk/zigbee-herdsman-converters/pull/7015, can I merge this?

**Comment by devbis** [comment]
I don't have any objections. Though, this fork in it's current state it will not be supported by converters due to a different structure of clusters and the exactly same model/manufacturer.

**Comment by kwiateusz** [comment]
If it will not be supported then there is no point in adding, thanks for the information

**Comment by devbis** [comment]
@kwiateusz  It will be supported but without changes in pvvx's firmware https://github.com/pvvx/ZigbeeTLc/pull/52 only basic functionality (temperature + humidity) will be available with z2m. Either custom convertor will be required.

**Comment by pbranly** [comment]
Hi
Could you explain the role of those additional settings ?
In z2m there are 2 ways to change temperature and humidity calibration. Which one is used ? 
In addition there are also settings for confort min/max temp and humidity. Same question : what is the role of those new settings 
Thanks 
Phil

**Comment by devbis** [comment]
@pbranly Additional settings affect display values as well, while z2m internal calibration only modifies data in z2m and mqtt.
Comfort parameters is a configuration for happy/sad face on the display.

**Comment by kwiateusz** [comment]
I've pushed a new version which shouldn't interfere with devbis converter

**Comment by Koenkk** [comment]
@devbis @krzysztof-kwitt  can you do a final check?

**Comment by devbis** [comment]
LGTM

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
