### PR TITLE
Add IKEA Tradfri Signal Repeater 2.3.086

### PR DESCRIPTION
**Pull request by alpepi12**
From http://fw.ota.homesmart.ikea.net/feed/version_info.json

### CODE REVIEW

**Review by TheJulianJES — COMMENTED** [review]
I think Z2M automatically fetches IKEA OTAs from that IKEA URL.
Are you sure this is needed?

**Comment by alpepi12** [comment]
@TheJulianJES  I am not sure... The latest changes with ZHA OTA made all my ZHA update entities "Unknown". I opened an issue about this here: [https://github.com/home-assistant/core/issues/115116](https://github.com/home-assistant/core/issues/115116)

I read that this OTA master list was the way to go now. Perhaps I am mistaken, happy to discuss further.

**Comment by TheJulianJES** [comment]
ZHA also fetches IKEA images separately, though it uses a newer URL.

**Comment by alpepi12** [comment]
Ok thanks for letting me know. I can close the pull request.

Is it known why ZHA can no longer see available firmware images since 2024.4?
[https://github.com/home-assistant/core/issues/115116](https://github.com/home-assistant/core/issues/115116)

**Comment by Koenkk** [comment]
> Is it known why ZHA can no longer see available firmware images since 2024.4?

I don't know (I'm not maintaining ZHA but Zigbee2MQTT)

**Pull request closed without merging**
