### PR TITLE
Updated Hue images

### PR DESCRIPTION
**Pull request by TheJulianJES**
This PR updates many Hue images to version `1.116.3`.

Unfortunately, no release notes are provided as of creating this PR: https://www.philips-hue.com/en-us/support/release-notes/lamps

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Didn't notice any issues. Seems to be version `1.116.3` for all lights (or `67.116.3` for older TI-based lights).

**Comment by Koenkk** [comment]
Thanks!

**Comment by mundschenk-at** [comment]
With this FW update, the White & Color Ambiance devices should support the `Opal` and `Glisten` effects according to https://hueblog.com/2024/05/15/philips-hue-glisten-and-opal-now-for-more-lamps/.

**Comment by TheJulianJES** [comment]
I've also noticed that the LLC011 (1st gen Hue Bloom, RGB-only light) now accepts "color temperature" commands.
It converts them to RGB colors then, but they can now be controlled like all other Hue lights that are RGB+CCT.

Unfortunately, a long-standing issue with that device causing issues with (source) routing is still present, related thread:
- https://github.com/Koenkk/zigbee2mqtt/discussions/20835

**Pull request merged**
