### PR TITLE
Add Develco OTA images

### PR DESCRIPTION
**Pull request by samuli-as**
Added and updated images for Develco/Frient devices (from https://github.com/Develco-Products/frient_upgrade_images). I have tested some of these on my own devices:
EntrySensor_4.0.2.zigbee
HumiditySensor_4.0.1.zigbee
MotionSensor_4.0.6.zigbee
WaterLeakDetector_4.0.4.zigbee

The rest I do not have access to and have not tried. Some of the images actually are for devices not currently supported by Z2M.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by nilsbyte** [comment]
@Koenkk Develco products are identical to frient products. I have the EMIZB-141 Power Meter (https://github.com/Koenkk/zigbee2mqtt/issues/19042) but OTA is not available for that device. 

The correct firmware would be this one:

```
    {
        "fileVersion": 196866,
        "fileSize": 213826,
        "manufacturerCode": 4117,
        "imageType": 976,
        "sha512": "fa53c339b61a8980c3d8d42319be4f57aa088d98b8f87393a6fce84c2bd224079c26ca2b097f2a3bf042f629adf32bac90460e17d0b7a28864f244453e262baf",
        "url": "https://github.com/Koenkk/zigbee-OTA/raw/master/images/Develco/EMI2LED_3.1.2.zigbee",
        "path": "images/Develco/EMI2LED_3.1.2.zigbee"
    },
```

what has to be done to make that file available to the device?

**Comment by Koenkk** [comment]
@nilsbyte enabled OTA for it!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by nilsbyte** [comment]
@Koenkk Installed the `edge` version in HA just now, but the EMIZB-141 does not appear in the list of OTA devices. Is there something else that has to be done to make it work? Sorry, but i am fairly new to all the HA and Z2M matter.

**Comment by Koenkk** [comment]
Does it show at least `19.51.0` under the frontend -> settings -> about page? In case not, you are not running the latest version.

**Comment by nilsbyte** [comment]
Yes it has excactly this version. Is it possible that the update is not found because frient maybe has another manufacturer code as Develco? I dont know how the matching between firmware and device takes place.

**Comment by Koenkk** [comment]
Could you provide the data/database.db entry of your device?

**Comment by nilsbyte** [comment]
here is the relevant line from `/homeassistant/zigbee2mqtt/database.db`:*

```
{"id":21,"type":"EndDevice","ieeeAddr":"0x0015xxxxxxxxxxxx","nwkAddr":23506,"manufId":4117,"manufName":"frient A/S","powerSource":"Battery","modelId":"EMIZB-141","epList":[1,2],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":83,"inClusterList":[0,1,3,32,1794,2817,2821],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{}},"genPollCtrl":{"attributes":{"checkinInterval":14400}},"genPowerCfg":{"attributes":{"batteryVoltage":30,"batteryAlarmState":0,"batteryPercentageRemaining":200}},"seMetering":{"attributes":{"currentSummDelivered":[0,11084],"instantaneousDemand":256,"develcoInterfaceMode":0,"develcoPulseConfiguration":10000}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x0015xxxxxxxxxxxx","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x0015xxxxxxxxxxxx","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x0015xxxxxxxxxxxx","endpointID":1}],"configuredReportings":[],"meta":{}}},"dateCode":"2023-08-30 08:30","zclVersion":7,"interviewCompleted":true,"meta":{"configured":1651188520},"lastSeen":1717946532466,"checkinInterval":3600}
```
*removed the IEEE addresses.

Manufacturer ID is 4117, so this is correct.

**Comment by Koenkk** [comment]
I don't know why it doesn't show in the OTA tab (as it should now). Let's wait for the next z2m release and see if it works theere

**Comment by nilsbyte** [comment]
Z2M 1.39.0 in Home Assistant still does not list the frient EMIZB-141 in OTA. Can I do something to help find the cause?

**Comment by Koenkk** [comment]
- Does the device show up in the Z2M frontend OTA tab?
- Do you by any chance have a external converter for this device? Check your z2m configuration.yaml, if yes, remove it.

**Comment by nilsbyte** [comment]
Yes I am using an external converter because the features "Pulse configuration", "Interface Mode" and otheres are not in Z2M.

https://github.com/Koenkk/zigbee2mqtt/issues/19042

After disabling the external converter and completely rebooting the HA instance, the OTA update is available and working.

**Pull request merged**
