### PR TITLE
Updated Develco SMSZB-120 to 4.0.5

### PR DESCRIPTION
**Pull request by TheStigh**
Updated Develco SMSZB-120 to 4.0.5

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Krzysztonek** [comment]
HI @Koenkk ,
I've just updated my Frient SMSZB-120 to 4.0.5. However, since then I see many false positives(?) on this device.
I tried to remove this device from my Z2M list, and join it again from scratch. It brings no result: the siren is being activated from time to time (once per 3-4 minutes) without any visible reason. From now on, the only thing I can do is pressing the cover knob of the device to stop the siren for a while, but only for a while. After a few minutes, the siren is blaring again.
This is what I never met in the past, before installing this firmware 4.0.5 update. 
Can you, please, advise?

**Comment by Koenkk** [comment]
@TheStigh do you experience the same issues with this fw?

**Comment by RonniHolst** [comment]
I have the same as @Krzysztonek wrote here!! Not good for the wife factor :(

**Comment by TheStigh** [comment]
@Krzysztonek @RonniHolst 

Can you please confirm if you tested the warning before this did happen?
Or did you simply do the update and did not touch anything and the siren suddenly started?

There was introduced a "bug" where the {alarm:OFF} didnt' work. This is fixed and there are a PR for this.

Also, can you please inform what coordinator you guys are using?

**Comment by TheStigh** [comment]
> @TheStigh do you experience the same issues with this fw?

No, I dont. Though, I have an original Develco SMSZB-120.
I've talked to others last night with Frient where this did not happen, unless they tried the warning first hand (similar to pressing START from exposes).

**Comment by Krzysztonek** [comment]
I also haven't tested the warning before, just simply did the update, touching nothing else.
My coordinator is: `usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DExxxxxxx-if00`

**Comment by TheStigh** [comment]
Conbee II again. I dont have this coordinator and cannot test. I test on a zzh & Sonoff coordinator.
I cannot conclude, but in my mind the Conbee II causes many issues with Z2M users. I might be wrong. But the initial thought when these errors was written was "they probably got a Conbee II".

@Koenkk Any thoughts or comments on Conbee II? 

Have in mind - I don't make the firmware, I just publish it after receiveing the file from Develco.

**Comment by RonniHolst** [comment]
> @Krzysztonek @RonniHolst
> 
> Can you please confirm if you tested the warning before this did happen? Or did you simply do the update and did not touch anything and the siren suddenly started?
> 
> There was introduced a "bug" where the {alarm:OFF} didnt' work. This is fixed and there are a PR for this.
> 
> Also, can you please inform what coordinator you guys are using?

Yes I did test the warning - and was able to stop it again. But then I have had another device, and that just started beeping doing the night, and the only way I was to stop it was clicking on device. But a few minutes after it did start again..

So I am trying to downscale the firmware again, because I am also using the sirene for alarm at my house

**Comment by Krzysztonek** [comment]
Hi @RonniHolst 
>So I am trying to downscale the firmware again

How to perform the firmware downgrade? How should it be done? Never did it before... I even don't see such option in Z2M add-on. Any step-by-step hint?
I haven't saved the previous firmware... so maybe this is not feasible in this case?

**Comment by RonniHolst** [comment]
> Hi @RonniHolst
> 
> > So I am trying to downscale the firmware again
> 
> How to perform the firmware downgrade? How should it be done? Never did it before... I even don't see such option in Z2M add-on. Any step-by-step hint? I haven't saved the previous firmware... so maybe this is not feasible in this case?

I dont know all about it - but if you are using Home Assistant, then you can use 
https://github.com/Koenkk/zigbee2mqtt/issues/15795#issuecomment-1367358523

**Comment by waroen** [comment]
@TheStigh My Frient doesn't suddenly start it's siren. It does however no longer show the firmware revision after update. Shall try tomorrow to take it down and see if a can re-interview it properly. If not I'll remove and add again and see if that fixes it.

**Comment by TheStigh** [comment]
> @TheStigh My Frient doesn't suddenly start it's siren. It does however no longer show the firmware revision after update. Shall try tomorrow to take it down and see if a can re-interview it properly. If not I'll remove and add again and see if that fixes it.

First everybody should do if a device change behavior are to do a re-configure. If that doesn't work, delete it from Z2M using Force, restart Z2M and re-add it.

It works now on 4.0.2, 4.0.4 and will work as normal on 4.0.5 when the January release of Z2M are out. Tested on both original Develco and Frient.

**Comment by Krzysztonek** [comment]
>will work as normal on 4.0.5 when the January release of Z2M are out

This is really good news for the New Year! If so, then I won't do a firmware downgrade. For this time being, I'll temporarily remove the battery from my device, hoping that no fire will unleash by then.. ;)
Impatiently awaiting a new release of Z2M :)

**Comment by Krzysztonek** [comment]
I've just updated my Z2M to the last version 1.29.0-1. Now my Frient works fine for me. So far, so good! 
Thank you! <3

**Pull request merged**
