### PR TITLE
Tuya/Telink OTA TS011F _TZ3000_ky0fq4ho v1.0.13

### PR DESCRIPTION
**Pull request by PietPetrus**

### CODE REVIEW

**Comment by PietPetrus** [comment]
@Koenkk could you please merge this PR?
Thanks for the detailed guide, it was spot on.

**Comment by Koenkk** [comment]
Thanks!

**Comment by cloudbr34k84** [comment]
HI, i have this plug, and im wondering how i go about updating it?

**Comment by Gerben321** [comment]
Good question.

**Comment by dabepp** [comment]
Was this merged into the main FW yet? Still got a plug that turns off randonly...

**Comment by andrei-lazarov** [comment]
There are many updates submitted for Tuya TS011F devices, but it's a bit of a mess..
It's not clear which update is for which device, no release notes etc.

- [`v1.0.10`](https://github.com/Koenkk/zigbee-OTA/blob/master/images/Telink/oem_tl8258_zg_breaker_OTA_1.0.10.bin)
- [`v1.0.13`](https://github.com/Koenkk/zigbee-OTA/blob/master/not-in-manifest-images/Telink/1654157434-oem_zg_tl8258_plug_OTA_1.0.13.bin) <- image from this PR
- [`v1.0.14`](https://github.com/Koenkk/zigbee-OTA/blob/master/images/Telink/1686137326-oem_zg_tl8258_plug_OTA_1.0.14.bin)
- [`v1.1.0`](https://github.com/Koenkk/zigbee-OTA/blob/master/images1/Telink/1718263020-oem_zg_tl8258_plug_OTA_1.1.0.bin)
- [`v1.1.2`](https://github.com/Koenkk/zigbee-OTA/blob/master/images/Telink/1730081189-oem_zg_tl8258_plug_OTA_1.1.2.bin)
- [`v3.0.0`](https://github.com/Koenkk/zigbee-OTA/blob/master/images/Tuya/1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin)

Manually download the image and upload it to the device. 
(Use the custom firmware option in the Z2M user interface)

Previously the latest version `v3.0.0` was enabled for **all** TS011F - and it appears compatible, users did not report issues. But a Tuya engineer restricted it to 2 models (`ufv0gpfo`)

**Pull request merged**
