### PR TITLE
Add images for Bosch BTH-RM

### PR DESCRIPTION
**Pull request by burmistrzak**
Includes the following OTA images:

- `v0.3.7` for Bosch BTH-RM (230V)
- `v0.2.8` for Bosch BTH-RM (battery)

### CODE REVIEW

**Comment by Koenkk** [comment]
thanks!

**Comment by DerDreschner** [comment]
Just for documentation reasons: Both firmware updates were released on 14th of may ([Release Notes](https://www.bosch-smarthome.com/uk/en/release-notes/bosch-smart-home-system/2024-05-14.html)).

**Comment by mrrstux** [comment]
Thanks for pushing these images! I tried the one for BTH-RM 230v, from ZHA but it fails to apply it with an invalid image error:

homeassistant.exceptions.HomeAssistantError: Update was not successful: <Status.INVALID_IMAGE: 150>

**Comment by DerDreschner** [comment]
@mrrstux : Did you tried it only once? I had the same error message with one of my BSP-FZ2 from Bosch. Didn't happened on the second try.

**Comment by mrrstux** [comment]
@DerDreschner  No, I tried it 4 times already, with the same result.

**Comment by DerDreschner** [comment]
@mrrstux : Mhm, then I would guess it might have something to do with using ZHA instead of Z2M? But I don't have any `BTH-RM` to test the provided images.

**Comment by mrrstux** [comment]
@DerDreschner I do have a successful ota with ZHA, using one of the firmware from this repository,  on a Bosch Radiator Thermostat II, thus it could be some issue with the BTH-RM (230v) image. Just tried it again on a different BTH-RM (230v), unfortunately with the same result - I see the successful upload, but after 27 seconds, the invalid image error appears.

**Comment by DerDreschner** [comment]
@burmistrzak : You could try https://github.com/zigpy/zigpy-cli. I didn't used it yet, [but according to this comment](https://github.com/zigpy/zigpy/discussions/723#discussioncomment-5122703), it looks more robust and advanced as it would be able to get an uncorrupted ota file from multiple capture files.

If you need any help just let me know.

**Comment by mrrstux** [comment]
@burmistrzak Sadly, I do not have a SHC. Thanks again for trying to capture and share these images - really appreciated!

**Comment by Juan-ma** [comment]
Hello, I have all the stuff and I have managed to capture the OTA file. The bad thing is that I have multiple missing packets but the good thing is that I have the correct Image Block Response for 0x8D30 packet. I have reconstructed the file and tested with the command

`zigpy ota info 0x1209_0x3011_0x03076a30_MOD.ota`

and it shows "Validation result: ValidationResult.VALID"
I don't know how to upload the file, but I can paste the payload here:

1cf803301c19844204d0491c0129f1dd044604e0c9b204460191ff2905d140f231118648f9f7e5f93ae05143029107eb

I have edited the hex file using ImHex:

0x8D30   1c f8 03 30 1c 19 84 42 04 d0 49 1c 01 29 f1 dd
0x8D40   04 46 04 e0 c9 b2 04 46 01 91 ff 29 05 d1 40 f2
0x8D50   31 11 86 48 f9 f7 e5 f9 3a e0 51 43 02 91 07 eb

I hope you can reconstruct and upload the corrected file.

**Comment by eugengervais** [comment]
Hi all,
I add @Juan-ma payload to original file (0x1209_0x3011_0x03076a30.ota) at offset  0x8d30  and I am able to update Bosch Room thermostat II 230 V (BTH-RM230Z) to version 0.3.7. Btw, original file at that locations have all zeros.
Thanks

**Comment by h1nnak** [comment]
Hey, can someone upload the new Firmware "0x1209_0x3011_0x03076a30.ota"? 
Maybe also the fixed one @eugengervais @Juan-ma ?

**Comment by Juan-ma** [comment]
Here you are @h1nnak
[https://github.com/Juan-ma/zigbee-OTA/tree/master/images/Bosch](url)
Could you please confirm if you success updating your Thermostat?

**Comment by eugengervais** [comment]
Here is the file. I was able to update FW to ver 0.3.7.
[0x1209_0x3011_0x03076a30_mod.zip](https://github.com/user-attachments/files/17495651/0x1209_0x3011_0x03076a30_mod.zip)

**Comment by h1nnak** [comment]
> Here you are @h1nnak https://github.com/Juan-ma/zigbee-OTA/tree/master/images/Bosch Could you please confirm if you success updating your Thermostat?
> 
> Edit: I have made a pull request with the new file.

It works. Here some pictures. 





But, it is really the newest firmware? 
Because of the Date "20240227"

**Pull request merged**
