### PR TITLE
Add GL-C-006P Device firmware

### PR DESCRIPTION
**Pull request by Loic691**
Following https://github.com/Koenkk/zigbee-OTA/issues/461#issuecomment-2016813460
Add GL-C-006P Device firmware to OTA Z2M.
Modification of index.json file and add ota file

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Loic691** [comment]
Hi @Koenkk 
I tried the OTA update of another device (same ref), it fails instead local update wich is working.
What do you think about that ?
The log stops after downloading firmware.
After my device is hang and I have to reset it...

**Comment by Koenkk** [comment]
Does the local update work?

**Comment by Loic691** [comment]
Yes

**Comment by Koenkk** [comment]
So locally this update works and when doing it via zigbeeOTA it doesn't?

Can you provide the debug log for both cases?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

**Comment by Loic691** [comment]
Hi
I tested locally with an other firmware and another GL-C-006P device. 
This is the same issue.
We can't update device. Here's the log
I'm on last Z2M 1.36.1
When I launched the update, the device become hang and I have to reboot it and to pair it again...
Here's the log
```
2024-04-05 08:39:17Received MQTT message on 'zigbee2mqtt/0xbc33acfffe8b8f97/set' with data '{"state":"ON"}'
Debug 2024-04-05 08:39:17Publishing 'set' 'state' to '0xbc33acfffe8b8f97'
Debug 2024-04-05 08:39:20Received MQTT message on 'zigbee2mqtt/0xbc33acfffe8b8f97/set' with data '{"brightness":46}'
Debug 2024-04-05 08:39:20Publishing 'set' 'brightness' to '0xbc33acfffe8b8f97'
Debug 2024-04-05 08:39:33Update of '0xbc33acfffe8b8f97' failed (Error: OTA: Timeout, device did not request any image blocks)
Info 2024-04-05 08:39:33MQTT publish: topic 'zigbee2mqtt/0xbc33acfffe8b8f97', payload '{"brightness":254,"color_mode":"color_temp","color_temp":158,"color_temp_startup":370,"device":{"applicationVersion":0,"dateCode":"20210719","friendlyName":"0xbc33acfffe8b8f97","hardwareVersion":2,"ieeeAddr":"0xbc33acfffe8b8f97","manufacturerID":4687,"manufacturerName":"GLEDOPTO","model":"GL-C-006P","networkAddress":21689,"powerSource":"Mains (single phase)","softwareBuildID":"10276802","stackVersion":0,"type":"Router","zclVersion":3},"last_seen":"2024-04-05T08:37:02+02:00","linkquality":188,"state":"OFF","update":{"installed_version":10,"latest_version":12,"state":"available"},"update_available":null}'
Info 2024-04-05 08:39:33MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"0xbc33acfffe8b8f97"},"error":"Update of '0xbc33acfffe8b8f97' failed (OTA: Timeout, device did not request any image blocks)","status":"error","transaction":"t3ss7-1"}'
Error 2024-04-05 08:39:33Update of '0xbc33acfffe8b8f97' failed (OTA: Timeout, device did not request any image blocks)
Error 2024-04-05 08:39:37Publish 'set' 'state' to '0xbc33acfffe8b8f97' failed: 'Error: ZCL command 0xbc33acfffe8b8f97/11 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 21689 - 11 - 237 - 6 - 11 after 10000ms)'
Debug 2024-04-05 08:39:37Error: ZCL command 0xbc33acfffe8b8f97/11 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 21689 - 11 - 237 - 6 - 11 after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:492:47) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:760:28) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:591:24) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:46:17) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1129:32) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/devices/gledopto.ts:30:20) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:259:36)
Error 2024-04-05 08:39:57Publish 'set' 'brightness' to '0xbc33acfffe8b8f97' failed: 'Error: ZCL command 0xbc33acfffe8b8f97/11 genLevelCtrl.moveToLevelWithOnOff({"level":46,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 21689 - 11 - 238 - 8 - 11 after 10000ms)'
Debug 2024-04-05 08:39:57Error: ZCL command 0xbc33acfffe8b8f97/11 genLevelCtrl.moveToLevelWithOnOff({"level":46,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 21689 - 11 - 238 - 8 - 11 after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:492:47) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:760:28) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:591:24) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1150:13) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/devices/gledopto.ts:30:20) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:259:36) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)
```

**Comment by Loic691** [comment]
After another test without any change, i Try to update the firmware locally.
I will try on other device

**Pull request merged**
