### PR TITLE
Firmware for Legrand Netamo devices

### PR DESCRIPTION
**Pull request by bsheepdiy**
Add new manufacturer name Legrand (Id 4129)
These OTA firmware allow to unlock channel 11 limitation.

These files are captured using HTTP interception (MITM) between Legrand Hub and their official OTA web server.

These OTA updates for the following devices :
* imageType 16 (0x0010) https://www.zigbee2mqtt.io/devices/064888.html
* imageType 17 (0x0011) https://www.zigbee2mqtt.io/devices/067775_741811.html
* imageType 18 (0x0012) https://www.zigbee2mqtt.io/devices/067646.html

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Tonio16** [comment]
Hello

On my z2m ota doesn’t start since the legrand devices are not responding to the ota request.

Antoine

**Comment by bsheepdiy** [comment]
@Tonio16 which device you are trying to upgrade ?
I have some issue on battery device.

**Comment by Tonio16** [comment]
> @Tonio16 which device you are trying to upgrade ? I have some issue on battery device.

It’s two 064888. The ones on battery,  067773 and 067774, are not availables for ota.

Antoine

**Comment by Tibronx** [comment]
Hi

Silly question here but how complex is it to include other Legrand devices for ETA ?
Like 067726, 067797 & 067722 ?

Thomas

**Comment by bsheepdiy** [comment]
@Tonio16 these device use the new ZGP Protocol, I dont know howto upgrade.
@Tibronx 067726, 067797 & 067722 are main powered, so they could be upgraded.

You have to manually edit [legrand.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/legrand.js) file to add ota: ota.zigbeeOTA on object declaration. I supposed the device are fully recognized with zigbee2mqtt.

**Comment by Tonio16** [comment]
> @Tonio16 these device use the new ZGP Protocol, I dont know howto upgrade. @Tibronx 067726, 067797 & 067722 are main powered, so they could be upgraded.
> 
> You have to manually edit [legrand.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/legrand.js) file to add ota: ota.zigbeeOTA on object declaration. I supposed the device are fully recognized with zigbee2mqtt.

064888 is in the list, isn't it. 
Another user in a French forum is facing the same issue that the device is not responding to the update. 

Antoine

**Comment by Tonio16** [comment]
@bsheepdiy this is some info on my device. 

I don’t understand why last seen is set on N/A.

Antoine

`Friendly name
Module dressing
Last seen
N/A
Availability
[Disabled](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Device type
Router
Zigbee Model
Micromodule switch
Zigbee Manufacturer
[Legrand](https://www.zigbee2mqtt.io/supported-devices/#v=Legrand)
Description
Wired micromodule switch
Support status
Supported

IEEE Address
0x00047400000db744
Network address
0xB806
Firmware build date
20200708
Firmware version
001c
Manufacturer
Legrand
Model
[064888](https://www.zigbee2mqtt.io/devices/064888.html#legrand-064888)
Power
Interview completed
True`

`{
    "linkquality": 76,
    "state": "OFF",
    "update": {
        "state": "available"
    },
    "device": {
        "applicationVersion": 0,
        "dateCode": " \u000020200708\u0000\u0000\u0000\u0000\u0000",
        "friendlyName": "Module dressing",
        "hardwareVersion": 6,
        "ieeeAddr": "0x00047400000db744",
        "manufacturerID": 4129,
        "manufacturerName": " Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
        "model": "064888",
        "networkAddress": 47110,
        "powerSource": "Mains (single phase)",
        "softwareBuildID": "001c",
        "stackVersion": 66,
        "type": "Router",
        "zclVersion": 2
        }
}`

**Comment by mducommun** [comment]
Hi @bsheepdiy,
I have the same issues. I don't know how but one of my micromodule succesfully upgraded but the 5 others and my two power plug Legrand always answer "Device didn't respond to OTA request"

**Comment by mducommun** [comment]
I understand that Legrand want to keep control on the firmware distribution, but I still don't understand how it is suppose to work with Home Assistant.. Should I ask Legrand to send me the new firmware and put them in a folder on my gateway to do the upgrade?
The strangest thing is that 2 of my micromodule aggreed to update using zigbee2mqtt ota but the other says that the device didn't respond. Is there a process to upgrade them? Or is it just luck ?

**Comment by Tonio16** [comment]
Hello
@Koenkk 
I succeeded to update one module 064888 today.

I noticed during previous tries that the modules were answering, really seldom, to an OTA, status at 0.00% for few seconds, but it didn't go further. It failled quickly.
I had this behavior by starting an OTA and playing with on / off in Z2M frontend to help them to be "awake" and to react positively to the OTA annoucement.

Today, I tried again. After several times, I had 0.00% status and for once the OTA proceed further, at least for one module. For a second, no success at the moment.

May be it can help to understand what's happening here.


Antoine

**Comment by bsheepdiy** [comment]
@Tonio16 thanks for the feedback
I'm trying to update the battery remote control (067723), trying to wakeup the device and sending the OTA notity but nothing happens. 
According to Legrand doc :
`Trigger the update of the ZigBee device`
`The process to trigger an update for a ZigBee 3.0 device is described in the ZigBee documentation. Legrand modules automatically send update requests to the gateway`

I'll try to wait for a night ...

**Comment by mducommun** [comment]
Hi @Tonio16, 
What king of coordinator do you have?
I received few days ago my new one (a zigstar lan) replacing my conbee2 USB that I founded unstable (some devices lost connection)... So I tried to upadate my legrand device again and it works the first time for each!

**Comment by Tonio16** [comment]
> Hi @Tonio16, What king of coordinator do you have? I received few days ago my new one (a zigstar lan) replacing my conbee2 USB that I founded unstable (some devices lost connection)... So I tried to upadate my legrand device again and it works the first time for each!

A sonoff+ with the firmware of December 2021.


Antoine

**Comment by Loic691** [comment]
My 067647 roller shutter battery command don't respond to OTA request too.
The actuak firmware is 001e
Is there is solution to update it ?

**Comment by pipiche38** [comment]
> I understand that Legrand want to keep control on the firmware distribution, but I still don't understand how it is suppose to work with Home Assistant.. Should I ask Legrand to send me the new firmware and put them in a folder on my gateway to do the upgrade? The strangest thing is that 2 of my micromodule aggreed to update using zigbee2mqtt ota but the other says that the device didn't respond. Is there a process to upgrade them? Or is it just luck ?

You simply have to subscribe to their Operating Manual
https://developer.legrand.com/documentation/operating-manual/

For me keeping those files here expose you to compliance to copyright

**Comment by Loic691** [comment]
So I trier and there is only 2 devices with firmware available....
Legrand is not a good player for zigbee market. No other words

**Comment by nfnvsc** [comment]
@bsheepdiy do you happen to have the firmware for https://www.zigbee2mqtt.io/devices/067771.html
Thanks

**Comment by novisys** [comment]
hi,
@bsheepdiy bsheepdiy  can you explain us how did you managed to get the firmware plz ?
thanks

**Pull request merged**
