### PR TITLE
Sengled firmware

### PR DESCRIPTION
**Pull request by walthowd**
Adding Sengled firmware -- These can also be pulled direct from Sengled, but there is no endpoint to discover them. 

The endpoint the mobile app uses is here:
https://us-elements.cloud.sengled.com:443/zigbee/update/getUserFirmwareUpdateInfos.json

But requires authentication and only responds with the file path for bulbs that you have attached to your account and that are running an older firmware.

I faked the process with curl (below) and found these. 

* E12-N14
  * http://us-fm.cloud.sengled.com:8000/sengled/zigbee/firmware/RDL2016194_E12-N14_V0.0.9_20171018_release.ota
* E1C-NB6
  * http://us-fm.cloud.sengled.com:8000/sengled/zigbee/firmware/RDS2017028_E1C-NB6_V0.0.22_20180314.ota
* E11-N1EA
  * http://us-fm.cloud.sengled.com:8000/sengled/zigbee/firmware/1542704530003_RDS2017007_E11-N1EA_V0.0.49_20181026_release.ota
* E11-G13
  * http://us-fm.cloud.sengled.com:8000/sengled/zigbee/firmware/RDL2016091_1_E11-G13_V0.0.9_20170921_release.ota
* E1G-G8E
  * http://us-fm.cloud.sengled.com:8000/sengled/zigbee/firmware/1554860326863_RDS2018021_E1G-G8E_V10_20190405_release.ota 
* E11-U2E
  * http://us-fm.cloud.sengled.com:8000/sengled/zigbee/firmware/1555679540244_RDS2017009_E11_U2E_V42_20190418_release.ota
* E11-U3E
  * http://us-fm.cloud.sengled.com:8000/sengled/zigbee/firmware/1555679569017_RDS2017008_E11_U3E_V42_20190418_release.ota
* Z01-A19NAE26
  * http://us-fm.cloud.sengled.com:8000/sengled/zigbee/firmware/RDS2014011_Z01-A19_V0.0.46_20171028_release.ota

These are all the ones I could find -- To get a firmware download link you have to submit the device to your account:

`curl -H 'Host: us-elements.cloud.sengled.com:443' -H 'Cookie: JSESSIONID=YOURCOOKIEID' -H 'accept: */*' -H 'content-type: application/json' -H 'sid: YOURSID -H 'user-agent: Element/3.5.6 (iPhone; iOS 13.3.1; Scale/3.00)' -H 'accept-language: en-US;q=1' --data-binary '{"gatewayUuid":"YOURBRIDGEMAC","deviceList":[{"typeCode":"E11-N1EA","colorTemperature":0,"deviceVersion":"1","brightness":255,"productCode":"E11-N1EA","power":85,"onOff":1,"isOnline":1,"factoryName":"sengled","name":"Classic22E1","deviceUuid":"B0CE1814030622E1"}]}' --compressed 'https://us-elements.cloud.sengled.com:443/zigbee/device/addDevicesSuccess.json'`

Then you can query for available firmware:

`curl -H 'Host: us-elements.cloud.sengled.com:443' -H 'Cookie: JSESSIONID=YOURCOOKIEID' -H 'accept: */*' -H 'content-type: application/json' -H 'sid: YOURSID' -H 'user-agent: Element/3.5.6 (iPhone; iOS 13.3.1; Scale/3.00)' -H 'accept-language: en-US;q=1' --data-binary "{}" --compressed 'https://us-elements.cloud.sengled.com:443/zigbee/update/getUserFirmwareUpdateInfos.json'`

I repeated that process for this list of models:

E11-G13
E11-G14
E11-G23
E11-G23P
E11-G33
E11-G33P
E11-N11
E11-N1EA
E11-U21
E11-U2E
E11-U31
E11-U3E
E12-N12
E12-N13
E12-N14
E12-N15
E12-N1E
E13-A21
E13-N11
E14-N43
E14-U43
E1A-AC2
E1G-C5A
E21-N12
E21-U22
E21-U32
Z01-A19NAE26
Z01-A60EAB22
Z01-A60EAE27
Z01-CIA19NAE26

Here is the full output of what I got back:
https://pastebin.com/aRFWr9kR

Adding these with the scripts/add.js it appears two of the resulting files were duplicates. I received:

```
whowd@home:/tmp/zigbee-OTA$ node scripts/add.js /opt/homeassistant/zigpy_no_ota/RDL2016194_E12-N14_V0.0.9_20171018_release.ota 
Updated existing entry ({"fileVersion":9,"fileSize":116478,"manufacturerCode":4448,"imageType":3,"url":"https://github.com/Koenkk/zigbee-OTA/raw/master/images/Sengled/RDL2016194_E12-N14_V0.0.9_20171018_release.ota","path":"images/Sengled/RDL2016194_E12-N14_V0.0.9_20171018_release.ota"})
fs.js:1061
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'images/Sengled/RDL2016194_E12-N14_V0.0.9_20171018_release.ota'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at Object.<anonymous> (/tmp/zigbee-OTA/scripts/add.js:50:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Let me know if there is anything else needed.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, could you also make a PR for zigbee-herdsman-converters?

**Comment by walthowd** [comment]
@Koenkk Can you provide guidance on what would need to be done on zigbee-herdsman-converters? I had looked through there and I assumed everything would flow through the existing methods the Hue stuff was using? Am I missing something?

(Sorry, not a z2m user, just trying to help out and disseminate the firmware)

**Comment by Koenkk** [comment]
No problem, added it. Thanks for your contribution

**Comment by tobycth3** [comment]
@walthowd anyway to pull these again? There have been some new versions released over the past 3 years

**Comment by walthowd** [comment]
@tobycth3 That above process in OP can be repeated, though I'm not sure if you can add bulbs to your account without a valid hub/bridge -- LMK if you want to try, and/or I can give you test acct creds.

**Comment by tobycth3** [comment]
I did attempt the process above but was unsuccessful in obtaining my cookie
and session ID through fiddler. Each time I tried to decrypt the SSL
session, the app would no longer connect.

**Comment by tube0013** [comment]
I checked the other day, and didn't get anything new, the links I got seem to be what was download and are several years old.
```
{    "messageCode": "200"
    "info": "OK"
    "description": "正常"
    "gatewayList": [{        "gatewayUuid": "B0:CE:18:29:67:DB"
        "gatewayName": "Smart hub 67DA"
        "gatewayNewVersion": "V4.4.9"
        "gatewayNowVersion": "V4.4.9"
        "gatewayNewVersionUrl": "https://us-fm.cloud.sengled.com:443/sengled/zigbee/firmware/1597044252676_RDS2016003_N_GATEWAY.V4.4.9_20200716_(SVN581)_release.bin"
        "coordinatorNewVersion": "V0.0.5012"
        "coordinatorNowVersion": "V0.0.5012"
        "coordinatorNewVersionUrl": "https://us-fm.cloud.sengled.com:443/sengled/zigbee/firmware/1597044219987_RDS2016003_N_Z02_Hub_Coor_V0.0.5012_20200518(SVN528)_release.ebl"
        "updateStatus": 3
        "updateProgress": null
        "gatewayIsOnline": 0
        "updateFlagId": 3607232
        "deviceTypeList": [{            "deviceTypeCode": "E11-N1EA"
            "deviceTypeNewVersion": "V0.0.71"
            "deviceTypeNewVersionUrl": "https://us-fm.cloud.sengled.com:443/sengled/zigbee/firmware/1586412538195_RDS2017007_E11-N1EA_V0.0.71_20200311_release.ota"
            "updateProgress": null        }
 {            "deviceTypeCode": "E1G-G8E"
            "deviceTypeNewVersion": "V0.0.14"
            "deviceTypeNewVersionUrl": "https://us-fm.cloud.sengled.com:443/sengled/zigbee/firmware/1594881275531_RDSE2020003C0511_E1G-G8E_05m_10m_V0.0.14_20200711_release.ota"
            "updateProgress": null        }
 {            "deviceTypeCode": "E1C-NB7"
            "deviceTypeNewVersion": "V0.0.26"
            "deviceTypeNewVersionUrl": "https://us-fm.cloud.sengled.com:443/sengled/zigbee/firmware/1594944258723_RDSE2019001B0411_E1C_NB7_V0.0.26_20200708_release_(SVN404).ota"
            "updateProgress": null        }]
        "deviceList": [{            "deviceName": "Bulb 4"
            "deviceNewVersion": "V0.0.71"
            "deviceNowVersion": "V0.0.1"
            "updateStatus": 0
            "deviceIsOnline": 0
            "deviceUuid": "B0CE1814030622E1"
            "onOff": 0
            "productCode": "E11-N1EA"        }
 {            "deviceName": "Bulb 5"
            "deviceNewVersion": "V0.0.14"
            "deviceNowVersion": "V0.0.1"
            "updateStatus": 0
            "deviceIsOnline": 0
            "deviceUuid": "B0CE1814030622E6"
            "onOff": 0
            "productCode": "E1F-N5EW"        }
 {            "deviceName": "Bulb 1"
            "deviceNewVersion": "V0.0.9"
            "deviceNowVersion": "V0.0.0"
            "updateStatus": 3
            "deviceIsOnline": 0
            "deviceUuid": "B0CE181403373D39"
            "onOff": 0
            "productCode": "E11-G13"        }
 {            "deviceName": "Bulb 2"
            "deviceNewVersion": "V0.0.9"
            "deviceNowVersion": "V0.0.0"
            "updateStatus": 3
            "deviceIsOnline": 0
            "deviceUuid": "B0CE18140336FA57"
            "onOff": 0
            "productCode": "E11-G13"        }
 {            "deviceName": "Bulb 3"
            "deviceNewVersion": "V0.0.26"
            "deviceNowVersion": "V0.0.26"
            "updateStatus": 3
            "deviceIsOnline": 0
            "deviceUuid": "B0CE1814036C116F"
            "onOff": 0
            "productCode": "E1C-NB7"        }
 {            "deviceName": "Bulb 6"
            "deviceNewVersion": "V0.0.26"
            "deviceNowVersion": "V0.0.24"
            "updateStatus": 0
            "deviceIsOnline": 0
            "deviceUuid": "B0CE1814036C117F"
            "onOff": 0
            "productCode": "E1C-NB7"        }
 {            "deviceName": "Bulb 7"
            "deviceNewVersion": ""
            "deviceNowVersion": "V0.0.10"
            "updateStatus": 3
            "deviceIsOnline": 0
            "deviceUuid": "B0CE1817036C117F"
            "onOff": 0
            "productCode": "E1F-N5EW"        }
 {            "deviceName": "Bulb 8"
            "deviceNewVersion": ""
            "deviceNowVersion": "V0.0.7"
            "updateStatus": 3
            "deviceIsOnline": 0
            "deviceUuid": "B0CE1817038C117G"
            "onOff": 0
            "productCode": "E1F-N5EW"        }]    }]
    "releaseNotes": {        "gatewayRelease": "Color Effect"
        "coorRelease": "Color Effect"
        "deviceTypeReleaseList": [{            "deviceTypeCode": "Z01-A19NAE26"
            "releaseNote": "Bug fixed."        }
 {            "deviceTypeCode": "E11-G13"
            "releaseNote": "Bug fixed."        }
 {            "deviceTypeCode": "E12-N14"
            "releaseNote": "Bug fixed."        }
 {            "deviceTypeCode": "E11-N1EA"
            "releaseNote": "Light effect"        }
 {            "deviceTypeCode": "E1C-NB6"
            "releaseNote": "First Customer Ship."        }
 {            "deviceTypeCode": "E1G-G8E"
            "releaseNote": "Light Effect"        }
 {            "deviceTypeCode": "E11-U2E"
            "releaseNote": "First Customer Ship."        }
 {            "deviceTypeCode": "E11-U3E"
            "releaseNote": "First Customer Ship."        }
 {            "deviceTypeCode": "E1C-NB7"
            "releaseNote": "FCS"        }
 {            "deviceTypeCode": "E12-N1E"
            "releaseNote": "Light effect"        }
 {            "deviceTypeCode": "E21-N1EA"
            "releaseNote": "Light Effect"        }
 {            "deviceTypeCode": "E1F-N9G"
            "releaseNote": "FCS"        }
 {            "deviceTypeCode": "E22-N1E"
            "releaseNote": "Bug fix"        }
 {            "deviceTypeCode": "E31-N1E"
            "releaseNote": "Bug fix"        }
 {            "deviceTypeCode": "E23-N13"
            "releaseNote": "Bug fix"        }
 {            "deviceTypeCode": "E23-N11"
            "releaseNote": "Bug fix"        }]    }
    "success": true}
```

**Pull request merged**
