### PR TITLE
Add OTA 77 for Tuya TS011F_plug_1

### PR DESCRIPTION
**Pull request by freeDom-**

### CODE REVIEW

**Comment by freeDom-** [comment]
I intentionally removed it, because using the add.js script was overwriting the latest version of that firmware (v192). Using updateall.js changed a lot of other firmware entries, but did not add the version I uploaded to index.json.

Should I enter the information manually to index.json?

**Comment by Koenkk** [comment]
> was overwriting the latest version of that firmware (v192)

Do I understand correctly that the OTA you are trying to add is an older version than already available, if yes, why add this OTA?

**Comment by freeDom-** [comment]
Want to give people the possibility to downgrade if an update failed or make problems. Current OTA is available from Tuya anyways, but there is no way to get old OTAs

**Comment by stickpin** [comment]
Version older than 192 will cause those plugs to turn off for no reason. v192 the version that solves it.

**Comment by freeDom-** [comment]
V77 works great for me. No turning off. You can use the newer version if you like, but there is no harm in having an older OTA archived if someone has problems with v192. Description of this repo says that its purpose is collecting different OTAs...? What is bad about having multiple versions to choose from? There are also multiple versions for other devices

**Comment by freeDom-** [comment]
And that is exactly why my PR only contains the file...

**Comment by stickpin** [comment]
well, I will let @Koenkk decide if he wants to merge potentially problematic firmware into the repo.
https://github.com/Koenkk/zigbee2mqtt/issues/11648

**Comment by freeDom-** [comment]
That is simply not true! There is no problem with this firmware. Only certain devices have problems. I am using this firmware now since half a year and did not had any problems. Also some people.report that the same issue still exists for them with v192 which even proofs that it is not an issue with the firmware.

**Comment by Koenkk** [comment]
I'm fine with adding the OTA file to this repo without adding it to `index.json`. Can you also make a pr to update the `TS011F_plug_1` wiki on how to load this firmware on the device? (via https://www.zigbee2mqtt.io/guide/configuration/ota-device-updates.html#ota-index-override-file). Then the user can choose what to try.

**Comment by mrmaximas** [comment]
@stickpin @freeDom-  v192 at least includes undocumented overvoltage and overcurrent protection. I have experienced that when the voltage exceeds 260V for a short time, the plug turns off and will not turn on without external intervention. This was a very unpleasant surprise for me. The seller confirmed it. 
I am looking for a way how to downgrade FW form v192 (3.0.0 in SL app)
Please help me

**Comment by freeDom-** [comment]
> @stickpin @freeDom- v192 flashed to the _TZ3000_w0qqde0g at least includes undocumented overvoltage and overcurrent protection. I have experienced that when the voltage exceeds 260V for a short time, the plug turns off and will not turn on without external intervention. This was a very unpleasant surprise for me. The seller confirmed it. I am looking for a way how to downgrade FW form v192 (3.0.0 in SL app) Please help me

You can flash the firmware attached to the commit of this PR and see if that works for you (images/Telink/1654157434-oem_zg_tl8258_plug_OTA_1.0.13.bin is the file, which is OTA v77)
A documentation on how to install local OTA files can be found here: https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#local-ota-index-and-firmware-files

I did not make the effort to further work on this PR, but I can pickup the work and enhance the documentation to get this PR merged. Than you would only need to modify the index.json file and do not need to download the firmware.

**Comment by mrmaximas** [comment]
@freeDom- Thanks! Have you tried to apply voltage above 260v to the plug with this oldest firmware?

**Comment by freeDom-** [comment]
I would not recommend to put overvoltage to the plug and I did not try it out. Afaik overvoltage protection was added in v192, so it should not turn itself off.
I did not have any problems at all after going back to the OTA v77 firmware and I am running it now on 6 plugs for over a year.

**Comment by freeDom-** [comment]
@Koenkk can you re-open this PR or should I create a new one? I recreated a PR for the documentation: https://github.com/Koenkk/zigbee2mqtt.io/pull/2892

**Comment by mrmaximas** [comment]
@Koenkk how about adding a fw version selection via ota feature?

**Comment by Koenkk** [comment]
I think the pr from @freeDom- is good enough for now

**Comment by mrmaximas** [comment]
@Koenkk do I understand correctly that I can now rollback the firmware from 192 to 77 via z2m ui?

**Comment by freeDom-** [comment]
> No, it is not possible via UI and probably won't be possible in the future. What you require is a major feature that would be a huge effort. It is also an uncommon edge case and there is a documented way how to install a different firmware if required.

Please use @ highlights sparse and only when necessary. I am sure Koenkk has a lot of other things to do.

**Comment by mrmaximas** [comment]
@freeDom- thanks! It possible to help me revert 192 to 77?
what i do:
1. add my_ota_index.json to z2m data dir
2. add to my_ota_index.json this code:
```
[
    {
        "fileVersion": 77,
        "fileSize": 307682,
        "manufacturerCode": 4417,
        "imageType": 54179,
        "sha512": "97ea8413e8ab662f2bebf3b013b3030754cbc2c0744b91b14741fff17a2d8d99e7088aa22a3b6e43b3595ccd65433f96d32516fc057fddcc13a816c921af8c97",
        "url": "https://github.com/Koenkk/zigbee-OTA/raw/master/images/Telink/1654157434-oem_zg_tl8258_plug_OTA_1.0.13.bin"
    }
]
```
3. press check to update then recieved message:

 `zhc:ota:common: Firmware on '0xa4c1387ae961ba19' (TS011F) is newer than latest firmware online.`
 
 how to fix it?
 thanks!

**Comment by mrmaximas** [comment]
> No, it is not possible via UI and probably won't be possible in the future. What you request is a major feature that would be a

Thanks! I was able to rollback the firmware to 77, but the firmware file had to be placed locally.

```
[
    {
        "fileVersion": 77,
        "fileSize": 307682,
        "manufacturerCode": 4417,
        "imageType": 54179,
        "sha512": "97ea8413e8ab662f2bebf3b013b3030754cbc2c0744b91b14741fff17a2d8d99e7088aa22a3b6e43b3595ccd65433f96d32516fc057fddcc13a816c921af8c97",
        "url": "/Users/m/zigbee2mqtt/data/1654157434-oem_zg_tl8258_plug_OTA_1.0.13.bin",
	"force": true
    }
]
```

**Comment by freeDom-** [comment]
> > No, it is not possible via UI and probably won't be possible in the future. What you request is a major feature that would be a
> 
> Thanks! I was able to rollback the firmware to 77, but the firmware file forced to be placed locally.
> 
> ```
> [
>     {
>         "fileVersion": 77,
>         "fileSize": 307682,
>         "manufacturerCode": 4417,
>         "imageType": 54179,
>         "sha512": "97ea8413e8ab662f2bebf3b013b3030754cbc2c0744b91b14741fff17a2d8d99e7088aa22a3b6e43b3595ccd65433f96d32516fc057fddcc13a816c921af8c97",
>         "url": "/Users/m/zigbee2mqtt/data/1654157434-oem_zg_tl8258_plug_OTA_1.0.13.bin",
> 	"force": true
>     }
> ]
> ```

Great that you managed to downgrade :). Can you share your experience if voltage protection indeed is disabled in v77?

Until this PR is merged (and a new version is released) one needs to manually store the file as mentioned above.

**Comment by mrmaximas** [comment]
@freeDom- now i got another problem - some of my such plugs work in classic tuya system via SL app, now the app keeps suggesting to update the firmware everytime i open SL with this plugs ;)

**Comment by freeDom-** [comment]
OK Idont use Smart Life App, but this sounds as expected behavior to me.

**Comment by freeDom-** [comment]
@Koenkk Since the PR which goes along with this one for the documentation (https://github.com/Koenkk/zigbee2mqtt.io/pull/2892) has been merged, can you open this PR and merge it as well?

Or should I create a new PR containing the same changes?

**Comment by Koenkk** [comment]
Merged, thanks @freeDom- !

**Comment by mrmaximas** [comment]
@freeDom- rollback the firmware to 77 unfortunately did not help to solve the plug shut-off problem. I have the same behaviour. 
Screenshot 2024-07-20 at 16 45 34
@
Screenshot 2024-07-20 at 16 48 04

**Comment by satter** [comment]
I have a couple of TS011F _TZ3000_dksbtrzs plugs with installed firmware version 192
If I do an OTA updates check from the web interface this will result in error:
```
zhc:ota:common: Firmware on '0xa4c1384d2bf66838' (TS011F) is newer than latest firmware online.
```
Is version 80 really newer than v192 I have installed? How do I find semver (e.g. 1.0.13) for file version 192?

**Comment by mrmaximas** [comment]
> I have a couple of TS011F _TZ3000_dksbtrzs plugs with installed firmware version 192 If I do an OTA updates check from the web interface this will result in error:
> 
> ```
> zhc:ota:common: Firmware on '0xa4c1384d2bf66838' (TS011F) is newer than latest firmware online.
> ```
> 
> Is version 80 really newer than v192 I have installed? How do I find semver (e.g. 1.0.13) for file version 192?

v 80 this is 1.10.0 in TUYA 
V 192 this is 3.0.0 in TUYA but latest TUYA version for _TZ3000_dksbtrzs is  1.10.0

**Pull request merged**
