### PR TITLE
Adds Xiaomi Plug OTA v30

### PR DESCRIPTION
**Pull request by AlexxIT**
For model `lumi.plug`. Because you can't update plug to latest fw if they have a firmware version below 30.
You need update to v30 fw and only then to v90:
https://t.me/xiaomi_gw_v3_hack/49948

### CODE REVIEW

**Comment by Koenkk** [comment]
This image won't be used if it is not in https://github.com/Koenkk/zigbee-OTA/blob/master/index.json

**Comment by AlexxIT** [comment]
I know this. But someone can add two step update logic after this pull request.

**Comment by Koenkk** [comment]
That should be added first then, otherwise it makes no sense to merge this pr.

**Comment by u17194907425** [comment]
@Koenkk good day. I need your advice. If I go ahead and do the following

1. update the https://github.com/Koenkk/zigbee-OTA/blob/master/index.json file using the procedure described here https://github.com/Koenkk/zigbee-OTA to point at the v30 FW 
2. Temporarily replace this file on my local HASS installation 
3. update all the plugs using standard zigbee2mqtt mechanisms
4. roll-back `index.json` changes

does it have a potential to work or do I miss something basic preventing this idea from being successful? In case the concept looks right can you suggest what is the right way do the step number 2?

Thanks

**Pull request closed without merging**
