### PR TITLE
Pulled from Zigpy

### PR DESCRIPTION
**Pull request by deonte1threatt**
Pulled from https://github.com/zigpy/zigpy/discussions/660?sort=new

### CODE REVIEW

**Comment by deonte1threatt** [comment]
Let me know if this meets all requirements or if i need anything more. I found a few FW files on this page that can be imported into here.

**Comment by Koenkk** [comment]
What is broken with the IKEA feed?

**Comment by deonte1threatt** [comment]
> What is broken with the IKEA feed?

Unless there's a different feed but the one I've been seeing around the interwebs hasn't worked. 

I also haven't gotten any updates in years for my IKEA stuff

**Comment by Koenkk** [comment]
For what device is this firmware?

**Comment by deonte1threatt** [comment]
Its for SYMFONISK sound remote, gen 1 (e1744)

**Comment by Koenkk** [comment]
The http one, which Z2M uses still works: http://[fw.ota.homesmart.ikea.net/feed/version_info.json](http://fw.ota.homesmart.ikea.net/feed/version_info.json)

**Comment by deonte1threatt** [comment]
Ahh had to use a different browser. 

The latest update im seeing in Z2M is 2.1.024. Online it has versions up to 24.4.5. I can't seem to find the firmware in that JSON.

**Comment by Koenkk** [comment]
I see, please also make a PR to use `zigbeeOTA()` instead of `ikeaOTA()` here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/8a7f4e675a9a701ae3c1e090afea615c1e3e5bba/src/devices/ikea.ts#L805

**Comment by TheJulianJES** [comment]
Seems to be in the newer IKEA DIRIGERA feed: https://fw.ota.homesmart.ikea.com/DIRIGERA/version_info.json

**Comment by deonte1threatt** [comment]
Would it be best to add that feed for ikea devices instead of the change proposed by @Koenkk  ?

**Comment by Koenkk** [comment]
I did not check it in depth, but it seems that not all firmwares are in the DRIGERA one, e.g. `image_type` `10241` is missing.

Maybe we should add all the TRADFRI firmwares to this repo and setup a CI pipeline which updates it from the IKEA sites weekly?

**Pull request closed without merging**
