### PR TITLE
Update Ubisys range to new firmwares - ubisys Zigbee Stack 4.0.3

### PR DESCRIPTION
**Pull request by geirra**
New firmware for the D1 dimmer was released 25.01.23

Changelog here:
https://www.ubisys.de/en/support/firmware/changelog-d1/

### CODE REVIEW

**Comment by geirra** [comment]
Added all the other firmwares also.
ref: https://www.ubisys.de/en/support/firmware/

**Comment by Koenkk** [comment]
@sjorge did you already check these?

**Comment by sjorge** [comment]
Yes, but I'm confused why they are here too... AFAIK ota/ubisys.js fetches these directly from the ubisys website!

**Comment by Koenkk** [comment]
I see, we also don't use this (Zigbee-OTA) repo for Ubisys devices. @geirra what is the reason for this pr?

**Comment by geirra** [comment]
Error from my side, didn`t know that these where pulled for ubisys.js in the herdsman-converts.

I'll close this @Koenkk

**Comment by sjorge** [comment]
@Koenkk I guess we should remove the old once as they are not being used?

**Comment by geirra** [comment]
the older entries in index.js is the reason why i tought the firmware should be provided this way.
So might be a good idea

**Comment by Koenkk** [comment]
Removed them!

**Pull request closed without merging**
