### PR TITLE
Add terncy smart dial fw

### PR DESCRIPTION
**Pull request by tube0013**

### CODE REVIEW

**Review by sjorge — COMMENTED** [review]
You might want to drop the .DS_store file

**Comment by Koenkk** [comment]
Can you add it using the instructions provided here: https://github.com/Koenkk/zigbee-OTA#adding-new-and-updating-existing-ota-files  (otherwise it's not added to the index.json).

**Comment by tube0013** [comment]
sorry I can't get the add.js to run on my mac:

```
zigbee-OTA % /usr/local/opt/node/bin/node scripts/add.js ~/Documents/Terncy/TERNCY-SD01_v46.OTA
~/Documents/GitHub/zigbee-OTA/scripts/add.js:1
qconst path = require('path');
       ^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by Koenkk** [comment]
I see  `qconst ` in your script but this is not what is in https://github.com/Koenkk/zigbee-OTA/blob/a02a4cb33f7c46b4d2916805bfcad582124ec975/scripts/add.js#L1 looks like add.js contains some local changes on your side.

**Comment by tube0013** [comment]
thanks I most of fat fingered that when I added Terncy to the list in the file.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
