### PR TITLE
Revert "Updated Sonoff TRVZB v1.1.4 OTA image"

### PR DESCRIPTION
**Pull request by Koenkk**
Reverts Koenkk/zigbee-OTA#450

Reverted on request of SONOFF

### CODE REVIEW

**Comment by riperez** [comment]
Same situation here. Getting (OTA: Update failed with reason: 'invalid image') when trying to force it back to 1.1.1 locally.

**Comment by Koenkk** [comment]
@lcheng33775823 could you help with this?

**Comment by dariusffm** [comment]
Hi here is complete debug log
Best regards, Darius



debug 2024-03-01 22:55:27Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/update' with data '{"id":"Sonoff-Termo-Dachgeschoss","transaction":"8yih3-3"}'
info 2024-03-01 22:55:27Updating 'Sonoff-Termo-Dachgeschoss' to latest firmware
debug 2024-03-01 22:55:29Received Zigbee message from 'Sonoff-Termo-Dachgeschoss', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20240131","swBuildId":"1.1.4"}' from endpoint 1 with groupID 0
debug 2024-03-01 22:55:29OTA: Updating to latest '0xb0c7defffee8caea' (TRVZB)
debug 2024-03-01 22:55:29OTA: Using endpoint '1'
debug 2024-03-01 22:55:29Received Zigbee message from 'Sonoff-Termo-Dachgeschoss', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20240131","swBuildId":"1.1.4"}' from endpoint 1 with groupID 0
debug 2024-03-01 22:55:29Received Zigbee message from 'Sonoff-Termo-Dachgeschoss', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":4356,"imageType":8199,"manufacturerCode":4742}' from endpoint 1 with groupID 0
debug 2024-03-01 22:55:29OTA: Got request '{"fieldControl":0,"manufacturerCode":4742,"imageType":8199,"fileVersion":4356}'
debug 2024-03-01 22:55:29ZigbeeOTA: Getting image metadata for 'TRVZB'
debug 2024-03-01 22:55:29ZigbeeOTA: Downloaded main index
debug 2024-03-01 22:55:29ZigbeeOTA: Loading override index '/config/zigbee2mqtt/my_index.json'
debug 2024-03-01 22:55:29OTA: Getting new image for '0xb0c7defffee8caea' (TRVZB), latest meta {"fileVersion":4353,"fileSize":326702,"url":"https://github.com/Koenkk/zigbee-OTA/raw/master/images/Sonoff/trvzb_v1.1.1.ota","sha512":"b132f02055dffcbf55ccf94f164f1cc1fedb350be4755b56a8da1c3c51ae6814bba3e8650376ce76a0783394eae1315e912deba917efd4f36557c92068b437ef","force":true}
debug 2024-03-01 22:55:29OTA: Downloading firmware image from 'https://github.com/Koenkk/zigbee-OTA/raw/master/images/Sonoff/trvzb_v1.1.1.ota' using the zigbeeOTA custom CA certificates
debug 2024-03-01 22:55:30OTA: Update checksum validation succeeded for '0xb0c7defffee8caea' (TRVZB)
debug 2024-03-01 22:55:30OTA: Get new image for '0xb0c7defffee8caea' (TRVZB), image header {"otaUpgradeFileIdentifier":{"type":"Buffer","data":[30,241,238,11]},"otaHeaderVersion":256,"otaHeaderLength":56,"otaHeaderFieldControl":0,"manufacturerCode":4742,"imageType":8199,"fileVersion":4353,"zigbeeStackVersion":2,"otaHeaderString":"vers:00001101,00001101\n\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","totalImageSize":326702}
debug 2024-03-01 22:55:30OTA: Got new image for '0xb0c7defffee8caea' (TRVZB)
debug 2024-03-01 22:55:30OTA: Starting upgrade
debug 2024-03-01 22:55:30Received Zigbee message from 'Sonoff-Termo-Dachgeschoss', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":4356,"imageType":8199,"manufacturerCode":4742}' from endpoint 1 with groupID 0
debug 2024-03-01 22:55:30OTA: Got upgrade end request for '0xb0c7defffee8caea' (TRVZB): {"status":150,"manufacturerCode":4742,"imageType":8199,"fileVersion":4356}
debug 2024-03-01 22:55:30OTA: Update failed with reason: 'invalid image'
debug 2024-03-01 22:55:30Update of 'Sonoff-Termo-Dachgeschoss' failed (Error: OTA: Update failed with reason: 'invalid image')
info 2024-03-01 22:55:30MQTT publish: topic 'zigbee2mqtt/Sonoff-Termo-Dachgeschoss', payload '{"battery":100,"battery_low":null,"child_lock":"UNLOCK","closing_steps":287,"frost_protection_temperature":7,"idle_steps":480,"linkquality":30,"local_temperature":22.6,"local_temperature_calibration":-1.5,"occupied_heating_setpoint":22,"open_window":"OFF","running_state":"idle","system_mode":"heat","update":{"installed_version":4356,"latest_version":4353,"state":"available"},"update_available":null,"valve_closing_limit_voltage":2585,"valve_motor_running_voltage":1290,"valve_opening_limit_voltage":1288,"weekly_schedule":{"friday":"00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16","monday":"00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16","saturday":"00:00/16 07:00/19 10:00/19 10:00/19 10:00/19 23:00/16","sunday":"00:00/16 07:00/19 10:00/19 10:00/19 10:00/19 23:00/16","thursday":"00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16","tuesday":"00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16","wednesday":"00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16"}}'
info 2024-03-01 22:55:30MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Sonoff-Termo-Dachgeschoss"},"error":"Update of 'Sonoff-Termo-Dachgeschoss' failed (OTA: Update failed with reason: 'invalid image')","status":"error","transaction":"8yih3-3"}'
error 2024-03-01 22:55:30Update of 'Sonoff-Termo-Dachgeschoss' failed (OTA: Update failed with reason: 'invalid image')
debug 2024-03-01 22:55:30Error: OTA: Update failed with reason: 'invalid image' at /app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:568:24
debug 2024-03-01 22:55:46Received Zigbee message from 'Temperature-Emilian', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2108}' from endpoint 1 with groupID 0
info 2024-03-01 22:55:46MQTT publish: topic 'zigbee2mqtt/Temperature-Emilian', payload '{"battery":100,"humidity":57.53,"linkquality":30,"temperature":21.08,"voltage":3000}'
debug 2024-03-01 22:55:47Received Zigbee message from 'Temperature-Emilian', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":5757}' from endpoint 1 with groupID 0
info 2024-03-01 22:55:47MQTT publish: topic 'zigbee2mqtt/Temperature-Emilian', payload '{"battery":100,"humidity":57.57,"linkquality":27,"temperature":21.08,"voltage":3000}'
debug 2024-03-01 22:55:58Saving state to file /config/zigbee2mqtt/state.json`

`

**Comment by Blumlaut** [comment]
Getting the same issue here as darius, it seems setting the thermostat to "heating" fully opens the valve now regardless of temperature settings now, so you have to manually set the trvzb to "Off" when you no longer want it to heat :confused:

**Comment by electronicm** [comment]
Only for reference:

There is already a discussion about the same content. https://github.com/Koenkk/zigbee2mqtt/discussions/21632#discussioncomment-8651855

**Comment by alienatedsec** [comment]
Fast-tracking the above - if you updated to `v1.1.4` and your TRV started working in a reverse-mode - It would be closing the valve when heating instead of opening it - try restoring to defaults as per the below screenshot. It worked for me and many others

image

**Pull request merged**
