### PR TITLE
Add verified image for Bosch Room thermostat II 230 V (BTH-RM230Z) version 0.3.7

### PR DESCRIPTION
**Pull request by Juan-ma**
I have upload the  is the verified image for Bosch Room thermostat II 230 V (BTH-RM230Z) versiopn 0.3.7
I have rebuilt the broken image from @burmistrzak in his pull-request [https://github.com/Koenkk/zigbee-OTA/pull/508#issue-2347787653](url) with the correct payload in the 0x8D30 packet.
The image file has been tested with the command:

`zigpy ota info 0x1209_0x3011_0x03076a30_MOD.ota`

and it shows "Validation result: ValidationResult.VALID"

### CODE REVIEW

**Comment by h1nnak** [comment]
It works.
[




](url)

**Comment by Koenkk** [comment]
Could you use the add.js script such that it get added to index.json?

**Comment by Juan-ma** [comment]
I'm sorry, I forgot it. Now it is.

**Comment by Koenkk** [comment]
thanks!

**Pull request merged**
