### PR TITLE
Add OTA images for GLEDOPTO GL-FL-005P, GL-FL-006P & GL-FL-008P

### PR DESCRIPTION
**Pull request by washcroft**
Also requires PR:
https://github.com/Koenkk/zigbee-herdsman-converters/pull/2167

### CODE REVIEW

**Comment by TheJulianJES** [comment]
"Aaron" (I guess it's their software developer) still wants to send me some OTAs for the new "Pro" series.
So I'm a bit curious on how you got these images. Did someone over at GLEDOPTO send them to you?

(Another note: I'm running firmware 0x000001 on my "Pro Dimmer" and it asks for an image with both imageType=0 and manufactureCode=0)

(Thanks for PR'ing this)

**Comment by washcroft** [comment]
@TheJulianJES Get whatever OTA images you can, then we collate them here :) Yes, these are from my contact at GLEDOPTO.

As mentioned on the other PR, only "V_1_0" onwards of their new Pro series products supports OTA, older stuff won't even bother checking if there is updated firmware.

**Comment by TheJulianJES** [comment]
> @TheJulianJES Get whatever OTA images you can, then we can collate them here :) Yes, these are from my contact at GLEDOPTO.
> 
> As mentioned on the other PR, only "V_1_0" onwards of their new Pro series products supports OTA, older stuff won't even bother checking if there is updated firmware.
> 
> I had some first release Pro products running "V_0_x" that I first had to manually bring up to V_1_0 using serial debug/programming.

Ah, just answered on the PR. I thought that V_1_0_0 is the first firmware that was ever put on the Pro series (current_file_version=1).
I'm they're somewhat providing OTA images (finally). Let's hope I get some more OTA images.

**Comment by Koenkk** [comment]
Thanks!

**Comment by 70MM13** [comment]
Do you know what the changes in these updates are?

**Pull request merged**
