### PR TITLE
Add lumi.airrtc.agl001 0.0.0_0925 OTA

### PR DESCRIPTION
**Pull request by astappiev**
I received an update for Aqara TVR via Aqara Home app. Surprisingly, only 1 of my 4 TVRs received this update and all 3 others stuck on `0.0.0_0825`. Let's see if I can update them via Z2M and don't break anything :D

```
{
    "deviceModel": "lumi.airrtc.agl001",
    "deviceName": "Smart Radiator Thermostat E1",
    "deviceOnline": 1,
    "did": "lumi.XXXXXXXXXXXXX",
    "firmwareType": "zigbee",
    "firmwareVersion": "0.0.0_0825",
    "real1Name": "My Home",
    "real2Name": "Living room",
    "real2PositionId": "real2.1034890116337352704",
    "realPositionId": "real1.1034889607740243968",
    "upgradeFirmware": {
        "createTime": 1669203302000,
        "downloadUrl": "https://cdn.aqara.com/cdn/opencloud-product/mainland/product-firmware/prd/lumi.airrtc.agl001/20221122180726_OTA_lumi.airrtc.agl001_0.0.0_0925_20221122_A6C469.ota",
        "fileSize": 261468,
        "firmwareCRC32": "A075FF63",
        "firmwareMD5": "6ca654b75bc2b40a63be51b072a6c469",
        "firmwareVersion": "0.0.0_0925",
        "imageType": "exe",
        "isForce": true,
        "isNecessary": 0,
        "part": "zigbee",
        "releaseDate": 1669289166000,
        "state": 2,
        "updateLog": "1. Optimize the button logic;\n2. Optimize the notification of abnormal temperature control;\n3. Fix known bugs.",
        "updateTime": 1669289166000,
        "upgradeTakesTime": 0
    }
}
```

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by MrCamby** [comment]
For me it does not work.
`Failed to check if update available for 'Badezimmer-Thermostat' (Failed to find endpoint which support OTA cluster)`

Firmware-Datum
    Jun 7 2022
Firmware-Version
    0.0.0_0025
    
 I tried using the my_index.json with the force flag enabled. Did not work either. Let me know if you need further informations.

**Comment by astappiev** [comment]
Actually, for me too, I wasn't able to update any of Aqara devices via zigbee2mqtt, always getting the error. And according to [this issue](https://github.com/Koenkk/zigbee2mqtt/issues/10660), not we alone.

**Comment by ifajardoj** [comment]
> same error here:

Failed to check if update available for '…………………..' (Failed to find endpoint which support OTA cluster)

Firmware-Datum
Jun 7 2022
Firmware-Version
0.0.0_0025

**Comment by alexanderek** [comment]
same issue

**Comment by heppo5959** [comment]
same issue here: Update of 'Thermostat Wohnzimmer' failed (Failed to find endpoint which support OTA cluster).

**Comment by Otnow** [comment]
> same issue here: Update of 'Thermostat Wohnzimmer' failed (Failed to find endpoint which support OTA cluster).

You can update the firmware to the current version in the following way: https://github.com/Koenkk/zigbee2mqtt/issues/13993#issuecomment-1346644669

**Pull request merged**
