### PR TITLE
Add firmware for Bosch RBSH-TRV0-ZB-EU

### PR DESCRIPTION
**Pull request by compujuckel**
This was extracted from a Zigbee packet capture, since Bosch doesn't provide official downloads.
Version 20221121 / 3.04.03

I successfully used this file to perform an OTA update on one of my thermostats using z2m.

OTA support PR: https://github.com/Koenkk/zigbee-herdsman-converters/pull/5283

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by mldytech** [comment]
> This was extracted from a Zigbee packet capture, since Bosch doesn't provide official downloads. Version 20221121 / 3.04.03
> 
> I successfully used this file to perform an OTA update on one of my thermostats using z2m.
> 
> OTA support PR: [Koenkk/zigbee-herdsman-converters#5283](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5283)

Is there any chance to also receive newer firmware captured by you? The [december update](https://www.bosch-smarthome.com/de/de/service/aktuelle-meldungen/release-infos/system-solutions/2022-12-07.html) seems very promising too, since the initial heating seems a bit slow. Thank you very much!

**Comment by niklasarnitz** [comment]
I could try and get the firmware, if someone could give me some instructions on how to do that.
I have a Sonoff Zigbee Stick and the SHC-I and two Thermostats available.

**Comment by mldytech** [comment]
> I could try and get the firmware, if someone could give me some instructions on how to do that. I have a Sonoff Zigbee Stick and the SHC-I and two Thermostats available.

That would be amazing!
Unfortunately I don't have the SHC-I. After a quick research, I found out that you can sniff zigbee traffic via [this](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#_3-sniffing-traffic) method. But maybe it's the best if we wait for @compujuckel s answer, since he already managed to do it.

**Comment by compujuckel** [comment]
@mldytech this OTA file *is* the December update :)
and yes, initial heating is still not good...

@niklasarnitz I already replied to you in the other thread: https://github.com/Koenkk/zigbee2mqtt/issues/14926#issuecomment-1416793215
The sniffing guide on the z2m website is pretty good, but Bosch's use of install codes makes it slightly harder.
You can't just sniff the network key when pairing a device, since that packet is encrypted with a key derived from the install code.
You have to:
- use AES-MMO to get the derived key
- add that key into Wireshark
- pair a device
- find the Device Announcement packet that contains the actual network key

**Comment by DerDreschner** [comment]
Today, I ordered an CC2531 as well as a SHC-I to get the latest firmware (january '23) of the Bosch Thermostat as well as the BSP-FZ2. May I ask you, @compujuckel , if I have any trouble in extracting the firmware?

**Comment by compujuckel** [comment]
Sure! Also, in case you haven't seen it yet: https://github.com/compujuckel/ZigbeeOtaExtractor

**Comment by pawelkw** [comment]
@DerDreschner Any luck getting the FW dump? I see there's been a couple of releases this year with multiple fixes.

**Comment by DerDreschner** [comment]
@pawelkw : Yes, I extracted them without any problem and uploaded it to this repo. The last few updates included no new firmware for the thermostat II. All bugfixes were in the bosch smart controller software only. That means that 3.05.05 is the latest version as of today. See also #394 .

**Comment by pawelkw** [comment]
> @pawelkw : Yes, I extracted them without any problem and uploaded it to this repo. The last few updates included no new firmware for the thermostat II. All bugfixes were in the bosch smart controller software only. That means that 3.05.05 is the latest version as of today. See also #394 .

I see. Thank you for the update and checking! Danke schön!

**Pull request merged**
